#!/usr/bin/env python3
"""Report where the fleet disagrees with itself about a device family's response shape.

A merged schema flattens disagreement into `required` and `x-optional`. That is the right contract
but the wrong diagnostic: it tells you a field is optional without telling you *which* sites,
models or firmware lack it, which is the part that decides whether the adapter needs a branch, a
default, or a bug report to the vendor.

This reads the observations behind a standard and writes the disagreement out in full:

  * fields present everywhere — the safe core an adapter may depend on
  * fields that split by model or by firmware — a real capability difference
  * fields that split by neither — present at some sites on the same model and firmware, which
    usually means configuration or device state, not capability
  * type conflicts — the same field returning different JSON types across the fleet
  * endpoints that never returned a record anywhere, which the contract cannot describe at all

Usage:
    python3 scripts/schema_divergence_report.py --schemas schemas --out schemas/DIVERGENCE.md
"""
import argparse
import json
from collections import defaultdict
from datetime import datetime
from pathlib import Path


def load(schemas_dir):
    obs = defaultdict(list)
    root = Path(schemas_dir) / "_observations"
    for fam_dir in sorted(p for p in root.iterdir() if p.is_dir()):
        for f in sorted(fam_dir.glob("*.json")):
            try:
                obs[fam_dir.name].append(json.loads(f.read_text()))
            except ValueError:
                continue
    return obs


def analyse(observations):
    """endpoint -> field -> facts about where it was seen and what type it had."""
    per_endpoint = defaultdict(lambda: {"bearing": [], "empty": [], "fields": defaultdict(lambda: {
        "sites": set(), "models": set(), "firmware": set(), "types": set()})})
    for doc in observations:
        meta = doc["x-observation"]
        tag = (meta.get("site", "?"), meta.get("model") or "?", meta.get("firmware") or "?")
        for ep, node in doc.get("endpoints", {}).items():
            if "x-error" in node:
                continue
            body = node.get("items", node)
            props = body.get("properties") or {}
            rec = per_endpoint[ep]
            if not props:
                rec["empty"].append(tag)
                continue
            rec["bearing"].append(tag)
            for name, spec in props.items():
                t = spec.get("type")
                f = rec["fields"][name]
                f["sites"].add(tag[0])
                f["models"].add(tag[1])
                f["firmware"].add(tag[2])
                for one in (t if isinstance(t, list) else [t]):
                    f["types"].add(one)
    return per_endpoint


def classify(per_endpoint):
    out = {}
    for ep, rec in per_endpoint.items():
        bearing = rec["bearing"]
        all_sites = {t[0] for t in bearing}
        all_models = {t[1] for t in bearing}
        universal, by_model, by_firmware, by_site, conflicts = [], [], [], [], []
        for name, f in sorted(rec["fields"].items()):
            non_null = f["types"] - {"null"}
            if len(non_null) > 1:
                conflicts.append((name, sorted(f["types"])))
            if f["sites"] == all_sites:
                universal.append(name)
                continue
            missing_models = all_models - f["models"]
            if missing_models and f["models"] != all_models:
                by_model.append((name, sorted(f["models"]), sorted(missing_models)))
            else:
                by_site.append((name, sorted(f["sites"]), sorted(all_sites - f["sites"])))
        out[ep] = {"bearing": bearing, "empty": rec["empty"], "universal": universal,
                   "by_model": by_model, "by_site": by_site, "conflicts": conflicts,
                   "all_sites": sorted(all_sites), "all_models": sorted(all_models)}
    return out


def render(results, schemas_dir):
    lines = [
        "---",
        "Title: Cambium Response Schema Divergence",
        "Category: device-reference",
        "Status: current",
        "Authority: primary — derived from the fleet sweep observations in schemas/_observations/",
        "Scope: Where devices of the same family disagree about their own response shape",
        f"Last reviewed: {datetime.now().strftime('%Y-%m-%d')}",
        "Summary: Per-endpoint breakdown of which response fields are universal across the fleet and which split by model, firmware or site, generated from the sweep rather than asserted.",
        "---",
        "",
        "# Cambium Response Schema Divergence",
        "",
        "Generated by `scripts/schema_divergence_report.py` from the observations in "
        "`schemas/_observations/`. Regenerate it rather than editing it; findings worth keeping as "
        "knowledge belong in [references/05_known-issues.md](../references/05_known-issues.md).",
        "",
        "A field listed under **universal** was present on every device that returned a record for "
        "that endpoint — an adapter may depend on it. Everything below that needs a branch, a "
        "default, or an explanation.",
        "",
        "## Contents",
        "",
    ]
    for family in sorted(results):
        lines.append(f"- [{family}](#{family.replace('.', '')})")
    lines.append("")

    for family, endpoints in sorted(results.items()):
        lines += [f"## {family}", ""]
        for ep, r in sorted(endpoints.items()):
            n_bearing, n_empty = len(r["bearing"]), len(r["empty"])
            lines += [f"### {family} — `{ep}`", ""]
            lines.append(f"Observed on **{n_bearing}** device(s) with a record"
                         + (f", empty on **{n_empty}**" if n_empty else "")
                         + f". Models: {', '.join(r['all_models']) or 'n/a'}.")
            lines.append("")
            if not n_bearing:
                lines += ["**No device anywhere returned a record for this endpoint.** The contract "
                          "cannot describe its shape. Empty at: "
                          + ", ".join(sorted({t[0] for t in r['empty']})) + ".", ""]
                continue
            lines.append(f"- **Universal fields:** {len(r['universal'])}")
            lines.append(f"- **Model-specific fields:** {len(r['by_model'])}")
            lines.append(f"- **Site-specific fields:** {len(r['by_site'])}")
            lines.append(f"- **Type conflicts:** {len(r['conflicts'])}")
            lines.append("")
            if r["by_model"]:
                lines += ["| Field | Present on | Absent on |", "| --- | --- | --- |"]
                for name, present, absent in r["by_model"][:60]:
                    lines.append(f"| `{name}` | {', '.join(present)} | {', '.join(absent)} |")
                if len(r["by_model"]) > 60:
                    lines.append(f"| … {len(r['by_model']) - 60} more | | |")
                lines.append("")
            if r["by_site"]:
                lines += ["Fields that vary by site rather than by model — same hardware, different "
                          "response, so configuration or device state rather than capability:", "",
                          "| Field | Missing at |", "| --- | --- |"]
                for name, _, missing in r["by_site"][:40]:
                    lines.append(f"| `{name}` | {', '.join(missing[:12])}"
                                 + (f" … +{len(missing) - 12}" if len(missing) > 12 else "") + " |")
                if len(r["by_site"]) > 40:
                    lines.append(f"| … {len(r['by_site']) - 40} more | |")
                lines.append("")
            if r["conflicts"]:
                lines += ["**Type conflicts** — the same field returns different JSON types across "
                          "the fleet. Each one is a portability hazard for any code that indexes it:",
                          "", "| Field | Types observed |", "| --- | --- |"]
                for name, types in r["conflicts"][:40]:
                    lines.append(f"| `{name}` | {', '.join(types)} |")
                lines.append("")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--schemas", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    obs = load(args.schemas)
    if not obs:
        raise SystemExit("no observations found")
    results = {fam: classify(analyse(docs)) for fam, docs in obs.items()}
    Path(args.out).write_text(render(results, args.schemas))
    total = sum(len(v) for v in results.values())
    print(f"{args.out}: {len(results)} families, {total} endpoints, "
          f"{sum(len(d) for d in obs.values())} observations")


if __name__ == "__main__":
    main()
