#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_NAME="$(basename "$0")"
TARGET_DIR="./skill-repomix"
FORCE=0
DRY_RUN=0

usage() {
  cat <<'EOF'
Usage:
  create-skill-repomix.sh [options]

Options:
  --target-dir PATH   Output directory. Default: ./skill-repomix
  --force             Overwrite an existing generated skill directory
  --dry-run           Show planned actions without writing files
  -h, --help          Show help
EOF
}

log() { printf '[%s] %s\n' "$SCRIPT_NAME" "$*"; }
die() { printf '[%s] ERROR: %s\n' "$SCRIPT_NAME" "$*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target-dir)
      [[ $# -ge 2 ]] || die "--target-dir requires a path"
      TARGET_DIR="$2"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
done

[[ -n "$TARGET_DIR" ]] || die "Target directory cannot be empty"
[[ "$TARGET_DIR" != "/" ]] || die "Refusing to write to /"
[[ "$TARGET_DIR" != "$HOME" ]] || die "Refusing to overwrite home directory"

MARKER=".skill-repomix-generated"

if [[ -e "$TARGET_DIR" ]]; then
  if [[ ! -f "$TARGET_DIR/$MARKER" && "$FORCE" -ne 1 ]]; then
    die "Target exists and is not marked as generated. Use --force to overwrite: $TARGET_DIR"
  fi
fi

run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf 'DRY-RUN:'
    printf ' %q' "$@"
    printf '\n'
  else
    "$@"
  fi
}

write_file() {
  local path="$1"
  local mode="${2:-0644}"
  local tmp
  tmp="$(mktemp)"
  cat > "$tmp"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "Would write $path"
    rm -f "$tmp"
    return
  fi
  mkdir -p "$(dirname "$path")"
  mv "$tmp" "$path"
  chmod "$mode" "$path"
}

if [[ "$DRY_RUN" -eq 1 ]]; then
  log "Would create skill at $TARGET_DIR"
else
  if [[ -e "$TARGET_DIR" && "$FORCE" -eq 1 ]]; then
    rm -rf "$TARGET_DIR"
  fi
  mkdir -p "$TARGET_DIR"
fi

write_file "$TARGET_DIR/$MARKER" <<'EOF'
Generated by create-skill-repomix.sh
EOF

write_file "$TARGET_DIR/SKILL.md" <<'EOF'
---
name: skill-repomix
description: Safely scopes, packages, compresses, validates, and routes repository context using Repomix CLI and Repomix MCP for Codex, Claude Code, local LLMs, audits, reviews, and reusable reference workflows.
version: 0.2.0
license: Apache-2.0
---

# Skill: Repomix Workflow

## Purpose

Use Repomix to create the smallest safe repository context needed for a task.

Supported outputs:

- Repomix MCP for dynamic repository discovery
- XML for structured static snapshots
- Markdown for human review
- JSON for pipelines
- compressed packs for architecture discovery and constrained local models
- pinned remote repository reference packs

## Audience and Authority

- `SKILL.md` is the authoritative behavioural contract for AI agents.
- `README.md` is the human-facing installation and operation guide.
- `AGENTS.md` governs maintenance of the skill package.
- Scripts and templates provide reusable supporting mechanics.
- Repository-specific governance overrides generic defaults in this skill.
- When agent behaviour conflicts with human installation guidance, `SKILL.md` governs agent behaviour.

## Trigger Conditions

Use this skill for:

- repository onboarding
- architecture analysis
- code-review context
- current-state snapshots
- change-review packs
- security-review packs
- remote FOSS repository inspection
- token reduction
- Repomix configuration
- Repomix MCP routing
- language-specific repository packaging

## Non-Trigger Conditions

Do not use Repomix as a replacement for:

- semantic code editing
- test execution
- runtime debugging
- Git mutation
- current package documentation
- static security analysis
- durable project memory

## Mandatory Workflow

1. Read project governance files.
2. Identify the exact task.
3. Detect repository language and type.
4. Select the smallest applicable profile.
5. Determine the token budget for the selected profile.
6. Apply project-specific include overrides.
7. Apply security exclusions.
8. Inspect projected token usage against the budget.
9. Apply the threshold decision from Token-Budget Thresholds.
10. Choose MCP or static output.
11. Choose compression or full source.
12. Generate the pack.
13. Validate security and output.
14. Execute the retry strategy if the output exceeds the budget.
15. Split the output or abort if retry attempts are exhausted; emit the prescribed run report.

## Routing Decisions

| Situation | Preferred route |
|---|---|
| Broad discovery with an MCP-capable client | Repomix MCP |
| Audit, handoff, or reproducible evidence | Static XML pack |
| Human and AI review | Markdown |
| Programmatic processing | JSON |
| Local LLM with constrained context | Targeted compressed XML |
| Exact implementation review | Full, uncompressed source |
| Remote FOSS reference | Pinned revision, compressed by default |

## Token-Budget Thresholds

Evaluate projected or actual token usage against the selected profile budget.

| Budget utilisation | Required action |
|---|---|
| 0–60% | Continue with the selected scope |
| 61–80% | Continue, but remove non-essential examples, broad documentation, and unrelated tests where safe |
| 81–100% | Narrow the pack to the directly relevant subsystem before final generation |
| Above 100% | Do not deliver the pack; execute the pack-too-large retry strategy |
| Unknown | Run token inspection or generate a narrowly scoped diagnostic pack first |

Budget utilisation = actual or estimated tokens / selected profile token budget × 100.

Thresholds apply to the configured budget of the selected profile, not to the model context window.

Compression MUST NOT be enabled solely because the budget is exceeded when exact implementation logic is required.

## Pack-Too-Large Retry Strategy

When projected or generated output exceeds the token budget:

1. Remove generated, archived, historical, example, fixture, and unrelated test content.
2. Restrict scope to the affected package, service, module, or subsystem.
3. Retain governance files and directly relevant dependency manifests.
4. Remove unrelated language ecosystems from mixed-repository profiles.
5. Enable compression only when exact implementation bodies are not required.
6. Recalculate or regenerate the pack.
7. Repeat for a maximum of three attempts.
8. If still over budget:
   - split the output into explicitly named logical packs; or
   - stop and report that the requested scope cannot fit safely.

The agent MUST NOT:

- silently truncate output;
- silently exceed the token budget;
- remove authoritative governance files;
- compress implementation-sensitive code merely to make it fit.

## Ambiguous Routing

When more than one route is valid:

1. Prefer the route with the smallest safe context footprint.
2. Prefer static output when reproducibility is required.
3. Prefer MCP when scope is unknown and interactive discovery is available.
4. Prefer full source over compression when implementation correctness matters.
5. Prefer project-specific governance over skill defaults.
6. If ambiguity materially affects safety, cost, privacy, or correctness, ask the user.
7. Otherwise, choose the safest route and record the decision.

The user or project owner is the escalation authority. The skill must not invent an additional approval authority.

## Compression

Use compression for:

- architecture discovery
- external repository research
- broad structural review
- constrained local models

Do not use compression for:

- debugging
- SQL correctness
- financial logic
- validation code
- security-sensitive implementation details
- exact error handling
- authentication or authorisation review

## Safeguards

MUST NOT:

- disable Repomix security scanning
- include `.env` files, credentials, private keys, tokens, databases, logs, caches, runtime state, archives, backups, or rollback data
- trust remote repository Repomix configuration
- silently follow a remote default branch
- package `/`, `$HOME`, or another over-broad path
- recursively include generated Repomix output
- treat compressed output as source-equivalent
- claim validation that was not executed

## Required Run Report

Every completed Repomix workflow MUST produce this structure.

### Repomix Execution Summary

| Field | Value |
|---|---|
| Task | |
| Repository | |
| Selected profile | |
| Repository type | |
| Output mode | MCP / static |
| Output format | XML / Markdown / JSON / plain |
| Included scope | |
| Excluded scope | |
| Compression | Enabled / disabled |
| Compression justification | |
| Token budget | |
| Estimated or actual token count | |
| Budget utilisation | |
| Retry attempts | |
| Output path | |
| Security scan | Pass / fail / not executed |
| Validation | Pass / fail / partial |
| Remaining risks | |

### Scope Decisions

- Authority files used:
- Included:
- Excluded:
- Assumptions:
- Routing decision:
- Retry actions:

### Result

State whether the generated pack is:

- safe to use;
- within budget;
- suitable for the intended consumer;
- complete enough for the requested task.

Do not report a security or validation pass unless the check was executed.
EOF

write_file "$TARGET_DIR/README.md" <<'EOF'
# skill-repomix

Reusable Repomix skill for Codex, Claude Code, and local LLM workflows.

## Audience

- `SKILL.md` defines how AI agents must behave when using Repomix.
- `README.md` explains installation, scripts, profiles, and human operation.
- `AGENTS.md` defines maintenance rules for the skill package.
- Scripts implement supporting mechanics; they do not replace the behavioural contract.
- The skill can be used behaviourally without copying every wrapper into each project.
- Wrappers are optional execution assets. Repomix MCP and static wrappers are complementary.

## Features

- four production wrapper scripts
- automatic language-profile detection
- per-language include and ignore profiles
- Repomix MCP routing policy
- secure static-pack generation
- project installer
- validation and test scripts

## Generate

```bash
./create-skill-repomix.sh
```

## Validate

```bash
skill-repomix/scripts/validate-skill.sh
skill-repomix/tests/test-skill-repomix.sh
```

## Wrappers

- `repomix-current`: project onboarding and current-state packs
- `repomix-review`: change-review packs with Git diffs
- `repomix-security`: security-focused context packs
- `repomix-reference`: pinned remote FOSS reference packs

## Profiles

See `profiles/README.md`.

## Licence

Apache-2.0
EOF

write_file "$TARGET_DIR/AGENTS.md" <<'EOF'
# Agent Maintenance Rules

- Preserve the profile schema in `docs/profile-schema.md`.
- Update tests when adding or changing profiles.
- Never weaken secret or mutable-state exclusions.
- Never add support for `--no-security-check`.
- Keep shell scripts portable across macOS and Linux.
- Avoid GNU-only commands.
- Update `CHANGELOG.md` for every functional change.
- Keep `SKILL.md` authoritative for workflow behaviour.
- Keep `templates/repomix-mcp-routing-policy.md` authoritative for routing policy.
- Token thresholds must remain synchronised between `SKILL.md` and `patterns/token-budgeting.md`.
- Run-report schema changes require updates to both `scripts/validate-skill.sh` and `tests/test-skill-repomix.sh`.
- Retry behaviour must not be weakened without an explicit security or correctness justification.
- Audience and authority boundaries between `SKILL.md` and `README.md` must remain explicit.
EOF

write_file "$TARGET_DIR/ARCHITECTURE.md" <<'EOF'
# Architecture

```text
Skill guidance
  -> language detection
  -> profile selection
  -> wrapper orchestration
  -> Repomix CLI or MCP
  -> validated context output
```

## Layers

- `SKILL.md`: operational workflow
- `profiles/`: language-specific scope
- `patterns/`: reusable decision rules
- `templates/`: files installed into projects
- `scripts/`: execution and installation
- `tests/`: validation fixtures and regression tests
EOF

write_file "$TARGET_DIR/AI_NAVIGATION.md" <<'EOF'
# AI Navigation

| Intent | Read |
|---|---|
| Learn the workflow | `SKILL.md` |
| Understand architecture | `ARCHITECTURE.md` |
| Install into a project | `scripts/install-skill-into-project` |
| Select a language profile | `profiles/README.md` |
| Add or modify a profile | `docs/profile-schema.md` |
| Change MCP routing | `templates/repomix-mcp-routing-policy.md` |
| Change compression rules | `patterns/compression-policy.md` |
| Validate the package | `scripts/validate-skill.sh` |
| Troubleshoot | `docs/troubleshooting.md` |
| Understand token thresholds | `patterns/token-budgeting.md` |
| Handle an oversized pack | `SKILL.md`, `patterns/token-budgeting.md`, `patterns/context-scoping.md` |
| Resolve routing ambiguity | `SKILL.md`, `patterns/static-pack-vs-mcp.md` |
| Understand agent vs human documentation | `SKILL.md`, `README.md`, `AGENTS.md` |
| Review report format | `SKILL.md` |
EOF

write_file "$TARGET_DIR/context-map.yaml" <<'EOF'
version: 1
authority:
  agent_behavior: SKILL.md
  human_operations: README.md
  maintenance: AGENTS.md
  token_policy: patterns/token-budgeting.md
  architecture: ARCHITECTURE.md
  routing_policy: templates/repomix-mcp-routing-policy.md
  profile_schema: docs/profile-schema.md
relationships:
  - source: SKILL.md
    governs:
      - run-reporting
      - token-budget-thresholds
      - retry-strategy
      - ambiguous-routing
  - source: scripts/detect-language-profile
    depends_on:
      - profiles/
      - docs/profile-schema.md
  - source: scripts/repomix-current
    depends_on:
      - profiles/base.json
      - templates/repomix.config.json
  - source: scripts/install-skill-into-project
    depends_on:
      - templates/
      - scripts/repomix-current
      - scripts/repomix-review
      - scripts/repomix-security
      - scripts/repomix-reference
  - source: tests/test-skill-repomix.sh
    validates:
      - scripts/
      - profiles/
      - templates/
      - SKILL.md
      - patterns/
  - source: README.md
    note: human-operations guidance only; does not override SKILL.md agent behaviour
EOF

write_file "$TARGET_DIR/CHANGELOG.md" <<'EOF'
# Changelog

## 0.2.0

- Added token-budget utilisation thresholds.
- Added deterministic oversized-pack retry, split, and abort behaviour.
- Added prescribed Repomix execution-report schema.
- Added ambiguous-routing escalation rules.
- Clarified agent-facing versus human-facing documentation authority.
- Added validation and test coverage for the new behavioural contract.

## 0.1.0

- Initial `skill-repomix` release.
- Added four Repomix wrapper scripts.
- Added Repomix MCP routing policy.
- Added project installer.
- Added language detector.
- Added Python, JavaScript/TypeScript, Go, Rust, Java/Kotlin, .NET, Ruby, PHP, shell/infrastructure, Ansible, Terraform, data/SQL, documentation, and mixed-monorepo profiles.
- Added validators, examples, and tests.
EOF

write_file "$TARGET_DIR/SCRATCHPAD.md" <<'EOF'
# Scratchpad

Non-authoritative temporary notes only.

Do not use this file as current project truth.
EOF

write_file "$TARGET_DIR/LICENSE" <<'EOF'
Apache License
Version 2.0, January 2004
http://www.apache.org/licenses/

Copyright 2026

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at the URL above.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.
EOF

write_file "$TARGET_DIR/.gitignore" <<'EOF'
.ai-context/
*.tmp
.DS_Store
EOF

write_file "$TARGET_DIR/templates/repomix.config.json" <<'EOF'
{
  "$schema": "https://repomix.com/schemas/latest/schema.json",
  "input": {
    "maxFileSize": 2000000
  },
  "output": {
    "filePath": ".ai-context/current-state.xml",
    "style": "xml",
    "compress": false,
    "instructionFilePath": "repomix-instruction.md",
    "fileSummary": true,
    "directoryStructure": true,
    "files": true,
    "removeComments": false,
    "removeEmptyLines": false,
    "showLineNumbers": true,
    "truncateBase64": true,
    "copyToClipboard": false,
    "topFilesLength": 20,
    "tokenBudget": 120000,
    "includeEmptyDirectories": false,
    "git": {
      "sortByChanges": true,
      "sortByChangesMaxCommits": 100,
      "includeDiffs": false,
      "includeLogs": false,
      "includeLogsCount": 20
    }
  },
  "include": [
    "README.md",
    "AGENTS.md",
    "ARCHITECTURE.md",
    "AI_NAVIGATION.md",
    "context-map.yaml",
    "CHANGELOG.md"
  ],
  "ignore": {
    "useGitignore": true,
    "useDotIgnore": true,
    "useDefaultPatterns": true,
    "customPatterns": [
      ".ai-context/**",
      "**/.env",
      "**/.env.*",
      "**/*.pem",
      "**/*.key",
      "**/*.p12",
      "**/*.pfx",
      "**/credentials/**",
      "**/secrets/**",
      "**/node_modules/**",
      "**/.venv/**",
      "**/venv/**",
      "**/__pycache__/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "**/runtime/**",
      "**/logs/**",
      "**/*.log",
      "**/*.db",
      "**/*.sqlite",
      "**/*.sqlite3",
      "**/backup/**",
      "**/backups/**",
      "**/rollback/**",
      "**/archive/**"
    ]
  },
  "security": {
    "enableSecurityCheck": true
  },
  "tokenCount": {
    "encoding": "o200k_base"
  }
}
EOF

write_file "$TARGET_DIR/templates/.repomixignore" <<'EOF'
.ai-context/
repomix-output.*
*.repomix.xml
*.repomix.md
*.repomix.json

.env
.env.*
**/.env
**/.env.*
*.pem
*.key
*.p12
*.pfx
credentials/
secrets/
**/credentials/**
**/secrets/**

*.db
*.sqlite
*.sqlite3
logs/
runtime/
tmp/
temp/
cache/
.cache/
**/logs/**
**/runtime/**
**/tmp/**
**/cache/**

node_modules/
.venv/
venv/
dist/
build/
coverage/
__pycache__/
.pytest_cache/
.mypy_cache/
.ruff_cache/

backup/
backups/
rollback/
archive/
*.zip
*.tar
*.tar.gz
*.tgz
*.7z

*.png
*.jpg
*.jpeg
*.gif
*.webp
*.pdf
*.mp3
*.wav
*.mp4
*.mov

.DS_Store
Thumbs.db
EOF

write_file "$TARGET_DIR/templates/repomix-instruction.md" <<'EOF'
# Repository Interpretation Rules

1. Treat project governance files as operational policy.
2. Treat architecture and navigation files as authority maps.
3. Prefer documents marked `CURRENT AUTHORITATIVE`.
4. Use `CURRENT SUPPORTING` only as supporting evidence.
5. Do not derive current state from `SUPERSEDED`, historical, archived, or generated material.
6. Do not modify cache, data, runtime, generated, backup, or rollback paths unless explicitly requested.
7. Cite repository paths and line numbers.
8. Distinguish verified facts, inferred conclusions, and unresolved assumptions.
9. Read the smallest relevant file set before proposing changes.
10. Preserve repository governance.
EOF

write_file "$TARGET_DIR/templates/repomix-mcp-routing-policy.md" <<'EOF'
# Repomix MCP Routing Policy

## Tool Boundaries

- Repomix MCP MUST be used for broad repository packaging, searchable snapshots, and remote repository context.
- Static Repomix packs SHOULD be used for reproducible audits, handoffs, fixed evidence, and local LLM input.
- Semantic-code tools SHOULD be used for symbol-aware navigation and editing.
- Context7 or official documentation MUST be used for current third-party documentation.
- Git and GitHub tools MUST be used for repository history, branches, commits, PRs, and mutation.
- Semgrep or another static analyser MUST be used for security and code-pattern analysis.
- Project-context or memory tools SHOULD be used for durable decisions, tasks, and state.
- Runtime and test tools MUST be used for behavioural validation.

## Routing Workflow

1. Identify the task.
2. Read governance and navigation files.
3. Select the smallest relevant subsystem.
4. Select a language profile.
5. Apply security exclusions.
6. Check token usage.
7. Choose MCP or static output.
8. Decide whether compression is appropriate.
9. Generate and validate output.
10. Report scope, format, compression, security status, and limitations.

## Security

- Security scanning MUST remain enabled.
- Secrets MUST be excluded before scanning.
- Remote Repomix configuration MUST NOT be trusted.
- Mutable local state MUST NOT be packed.
- Output MUST be reviewed before external upload.
EOF

write_file "$TARGET_DIR/templates/project-integration-checklist.md" <<'EOF'
# Project Integration Checklist

- [ ] Read project governance
- [ ] Detect language profile
- [ ] Review include scope
- [ ] Review secret and mutable-state exclusions
- [ ] Install project-local config
- [ ] Install `.repomixignore`
- [ ] Install instruction file
- [ ] Install required wrappers
- [ ] Confirm `.ai-context/` is ignored
- [ ] Run a token-budget smoke test
- [ ] Verify security scan remains enabled
- [ ] Document MCP versus static-pack routing
- [ ] Record rollback steps
EOF

write_file "$TARGET_DIR/templates/output/.gitkeep" <<'EOF'
EOF

write_file "$TARGET_DIR/profiles/README.md" <<'EOF'
# Language Profiles

Profiles define detection evidence, include patterns, ignore patterns, priority files, sensitive patterns, default compression, and token budget.

Available profiles:

- base
- python
- javascript-typescript
- go
- rust
- java-kotlin
- dotnet
- ruby
- php
- ansible
- terraform
- data-sql
- documentation
- mixed-monorepo
- justfile
- bash
EOF

# profile writer helper
write_profile() {
  local name="$1"
  write_file "$TARGET_DIR/profiles/$name.json"
}

write_profile base <<'EOF'
{
  "id": "base",
  "displayName": "Base",
  "description": "Cross-language governance and build metadata.",
  "detect": {"anyFiles": ["README.md", "AGENTS.md"], "anyDirectories": []},
  "include": ["README.md", "AGENTS.md", "ARCHITECTURE.md", "AI_NAVIGATION.md", "context-map.yaml", "CHANGELOG.md", "LICENSE*", "Dockerfile*", "compose*.yaml", "compose*.yml", "Makefile", "Taskfile*", "justfile"],
  "ignore": [".ai-context/**", "**/.env", "**/.env.*", "**/*.pem", "**/*.key", "**/*.db", "**/*.sqlite", "**/*.sqlite3", "**/node_modules/**", "**/.venv/**", "**/dist/**", "**/build/**", "**/coverage/**", "**/logs/**", "**/runtime/**", "**/cache/**", "**/backup/**", "**/backups/**", "**/rollback/**", "**/archive/**"],
  "priorityFiles": ["AGENTS.md", "ARCHITECTURE.md", "AI_NAVIGATION.md", "context-map.yaml"],
  "securitySensitivePatterns": ["**/.env*", "**/*.pem", "**/*.key", "**/credentials/**", "**/secrets/**"],
  "defaultCompression": false,
  "defaultTokenBudget": 120000,
  "notes": ["Always combine with a language-specific profile."]
}
EOF

write_profile python <<'EOF'
{
  "id": "python",
  "displayName": "Python",
  "description": "Python repositories.",
  "detect": {"anyFiles": ["pyproject.toml", "requirements.txt", "setup.py", "setup.cfg", "uv.lock"], "anyDirectories": ["src", "tests"]},
  "include": ["pyproject.toml", "uv.lock", "poetry.lock", "Pipfile", "Pipfile.lock", "requirements*.txt", "setup.py", "setup.cfg", "tox.ini", "pytest.ini", "mypy.ini", "ruff.toml", "src/**/*.py", "app/**/*.py", "tests/**/*.py", "scripts/**/*.py", "migrations/**/*.py"],
  "ignore": [".venv/**", "venv/**", "__pycache__/**", ".pytest_cache/**", ".mypy_cache/**", ".ruff_cache/**", "*.pyc", "*.pyo", "dist/**", "build/**", "*.egg-info/**", ".coverage", "htmlcov/**"],
  "priorityFiles": ["pyproject.toml", "uv.lock", "requirements*.txt"],
  "securitySensitivePatterns": ["**/.env*", "**/settings.local.py", "**/secrets.py"],
  "defaultCompression": false,
  "defaultTokenBudget": 120000,
  "notes": []
}
EOF

write_profile javascript-typescript <<'EOF'
{
  "id": "javascript-typescript",
  "displayName": "JavaScript and TypeScript",
  "description": "JavaScript and TypeScript repositories.",
  "detect": {"anyFiles": ["package.json", "tsconfig.json", "pnpm-lock.yaml", "yarn.lock"], "anyDirectories": ["src", "app", "pages"]},
  "include": ["package.json", "package-lock.json", "pnpm-lock.yaml", "yarn.lock", "bun.lock", "bun.lockb", "tsconfig*.json", "jsconfig*.json", "vite.config.*", "webpack.config.*", "next.config.*", "nuxt.config.*", "src/**/*.{js,jsx,ts,tsx,mjs,cjs}", "app/**/*.{js,jsx,ts,tsx}", "pages/**/*.{js,jsx,ts,tsx}", "components/**/*.{js,jsx,ts,tsx}", "server/**/*.{js,ts}", "tests/**/*.{js,jsx,ts,tsx}"],
  "ignore": ["node_modules/**", ".next/**", ".nuxt/**", ".output/**", "dist/**", "build/**", "coverage/**", "*.tsbuildinfo"],
  "priorityFiles": ["package.json", "tsconfig.json"],
  "securitySensitivePatterns": ["**/.env*", "**/secrets.*", "**/credentials.*"],
  "defaultCompression": false,
  "defaultTokenBudget": 120000,
  "notes": []
}
EOF

write_profile go <<'EOF'
{
  "id": "go",
  "displayName": "Go",
  "description": "Go repositories.",
  "detect": {"anyFiles": ["go.mod", "go.work"], "anyDirectories": ["cmd", "internal", "pkg"]},
  "include": ["go.mod", "go.sum", "go.work", "go.work.sum", "cmd/**/*.go", "internal/**/*.go", "pkg/**/*.go", "api/**/*.go", "tests/**/*.go", "**/*_test.go"],
  "ignore": ["vendor/**", "bin/**", "coverage.out", "*.test"],
  "priorityFiles": ["go.mod", "go.work"],
  "securitySensitivePatterns": ["**/.env*", "**/secrets.go"],
  "defaultCompression": false,
  "defaultTokenBudget": 120000,
  "notes": []
}
EOF

write_profile rust <<'EOF'
{
  "id": "rust",
  "displayName": "Rust",
  "description": "Rust repositories.",
  "detect": {"anyFiles": ["Cargo.toml", "Cargo.lock"], "anyDirectories": ["src", "crates"]},
  "include": ["Cargo.toml", "Cargo.lock", "rust-toolchain*", "rustfmt.toml", "clippy.toml", "src/**/*.rs", "tests/**/*.rs", "benches/**/*.rs", "examples/**/*.rs", "crates/**/Cargo.toml", "crates/**/*.rs"],
  "ignore": ["target/**"],
  "priorityFiles": ["Cargo.toml", "Cargo.lock"],
  "securitySensitivePatterns": ["**/.env*"],
  "defaultCompression": false,
  "defaultTokenBudget": 120000,
  "notes": []
}
EOF

write_profile java-kotlin <<'EOF'
{
  "id": "java-kotlin",
  "displayName": "Java and Kotlin",
  "description": "Java and Kotlin repositories.",
  "detect": {"anyFiles": ["pom.xml", "build.gradle", "build.gradle.kts"], "anyDirectories": ["src/main", "src/test"]},
  "include": ["pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts", "gradle.properties", "gradle/**/*", "src/main/**/*.java", "src/main/**/*.kt", "src/test/**/*.java", "src/test/**/*.kt"],
  "ignore": [".gradle/**", "target/**", "build/**", "out/**", "*.class"],
  "priorityFiles": ["pom.xml", "build.gradle", "build.gradle.kts"],
  "securitySensitivePatterns": ["**/application-local.*", "**/.env*"],
  "defaultCompression": false,
  "defaultTokenBudget": 130000,
  "notes": []
}
EOF

write_profile dotnet <<'EOF'
{
  "id": "dotnet",
  "displayName": ".NET",
  "description": ".NET repositories.",
  "detect": {"anyFiles": ["*.sln", "*.csproj", "*.fsproj", "global.json"], "anyDirectories": ["src", "tests"]},
  "include": ["*.sln", "*.slnx", "*.csproj", "*.fsproj", "*.vbproj", "Directory.Build.props", "Directory.Build.targets", "Directory.Packages.props", "global.json", "NuGet.config", "src/**/*.cs", "src/**/*.fs", "tests/**/*.cs", "tests/**/*.fs"],
  "ignore": ["bin/**", "obj/**", "TestResults/**", "*.user", "*.suo"],
  "priorityFiles": ["*.sln", "Directory.Build.props", "Directory.Packages.props"],
  "securitySensitivePatterns": ["**/appsettings.*.json", "**/.env*"],
  "defaultCompression": false,
  "defaultTokenBudget": 130000,
  "notes": []
}
EOF

write_profile ruby <<'EOF'
{
  "id": "ruby",
  "displayName": "Ruby",
  "description": "Ruby repositories.",
  "detect": {"anyFiles": ["Gemfile", "Gemfile.lock", "Rakefile"], "anyDirectories": ["app", "lib", "spec"]},
  "include": ["Gemfile", "Gemfile.lock", "*.gemspec", "Rakefile", "config.ru", "app/**/*.rb", "lib/**/*.rb", "config/**/*.rb", "spec/**/*.rb", "test/**/*.rb", "db/migrate/**/*.rb"],
  "ignore": [".bundle/**", "vendor/bundle/**", "tmp/**", "log/**", "coverage/**"],
  "priorityFiles": ["Gemfile", "Gemfile.lock"],
  "securitySensitivePatterns": ["config/master.key", "config/credentials*.yml.enc", "**/.env*"],
  "defaultCompression": false,
  "defaultTokenBudget": 110000,
  "notes": []
}
EOF

write_profile php <<'EOF'
{
  "id": "php",
  "displayName": "PHP",
  "description": "PHP repositories.",
  "detect": {"anyFiles": ["composer.json", "composer.lock"], "anyDirectories": ["src", "app", "routes"]},
  "include": ["composer.json", "composer.lock", "phpunit.xml*", "phpstan.neon*", "psalm.xml", "src/**/*.php", "app/**/*.php", "config/**/*.php", "routes/**/*.php", "tests/**/*.php", "database/migrations/**/*.php"],
  "ignore": ["vendor/**", "storage/logs/**", "bootstrap/cache/**", ".phpunit.cache/**"],
  "priorityFiles": ["composer.json", "composer.lock"],
  "securitySensitivePatterns": ["**/.env*", "config/*.local.php"],
  "defaultCompression": false,
  "defaultTokenBudget": 110000,
  "notes": []
}
EOF


write_profile ansible <<'EOF'
{
  "id": "ansible",
  "displayName": "Ansible",
  "description": "Ansible projects.",
  "detect": {"anyFiles": ["ansible.cfg", "requirements.yml", "requirements.yaml"], "anyDirectories": ["roles", "playbooks", "group_vars", "host_vars"]},
  "include": ["ansible.cfg", "requirements.yml", "requirements.yaml", "inventories/**/*.yml", "inventories/**/*.yaml", "group_vars/**/*.yml", "group_vars/**/*.yaml", "host_vars/**/*.yml", "host_vars/**/*.yaml", "roles/**/*.yml", "roles/**/*.yaml", "playbooks/**/*.yml", "playbooks/**/*.yaml", "collections/requirements.yml"],
  "ignore": ["**/vault*.yml", "**/vault*.yaml", "**/*secrets*.yml", "**/*secrets*.yaml", "**/.vault-password*"],
  "priorityFiles": ["ansible.cfg", "requirements.yml", "playbooks/**/*.yml"],
  "securitySensitivePatterns": ["**/vault*.yml", "**/vault*.yaml", "**/*secrets*.yml", "**/*secrets*.yaml"],
  "defaultCompression": false,
  "defaultTokenBudget": 90000,
  "notes": ["Vault and secret-variable files are excluded by default."]
}
EOF

write_profile terraform <<'EOF'
{
  "id": "terraform",
  "displayName": "Terraform",
  "description": "Terraform repositories.",
  "detect": {"anyFiles": ["terraform.lock.hcl"], "anyDirectories": ["modules", "environments"]},
  "include": ["**/*.tf", "**/*.tf.json", "**/*.tftpl", "terraform.lock.hcl", "modules/**", "environments/**"],
  "ignore": [".terraform/**", "*.tfstate", "*.tfstate.*", "crash.log", "crash.*.log", "*.tfvars", "*.auto.tfvars", "override.tf", "override.tf.json", "*_override.tf", "*_override.tf.json"],
  "priorityFiles": ["terraform.lock.hcl", "**/main.tf", "**/variables.tf", "**/outputs.tf"],
  "securitySensitivePatterns": ["*.tfvars", "*.auto.tfvars", "*.tfstate*"],
  "defaultCompression": false,
  "defaultTokenBudget": 90000,
  "notes": ["Variable files and state are sensitive by default."]
}
EOF

write_profile data-sql <<'EOF'
{
  "id": "data-sql",
  "displayName": "Data and SQL",
  "description": "SQL, dbt, and data-engineering repositories.",
  "detect": {"anyFiles": ["dbt_project.yml", "packages.yml"], "anyDirectories": ["sql", "queries", "models", "migrations"]},
  "include": ["sql/**/*.sql", "queries/**/*.sql", "models/**/*.sql", "migrations/**/*.sql", "dbt_project.yml", "packages.yml", "profiles.example.yml", "schema.yml", "models/**/*.yml", "models/**/*.yaml", "scripts/**/*.py"],
  "ignore": ["*.db", "*.sqlite", "*.sqlite3", "*.duckdb", "target/**", "dbt_packages/**", "logs/**", "profiles.yml", "*.csv", "*.parquet", "*.xlsx"],
  "priorityFiles": ["dbt_project.yml", "models/**/*.sql", "schema.yml"],
  "securitySensitivePatterns": ["profiles.yml", "*.csv", "*.parquet", "*.xlsx"],
  "defaultCompression": false,
  "defaultTokenBudget": 100000,
  "notes": ["Data files are excluded unless a bounded sample is explicitly requested."]
}
EOF

write_profile documentation <<'EOF'
{
  "id": "documentation",
  "displayName": "Documentation",
  "description": "Documentation-focused repositories.",
  "detect": {"anyFiles": ["mkdocs.yml", "docusaurus.config.js"], "anyDirectories": ["docs"]},
  "include": ["README.md", "AGENTS.md", "ARCHITECTURE.md", "AI_NAVIGATION.md", "CHANGELOG.md", "docs/**/*.md", "docs/**/*.mdx", "**/*.rst", "mkdocs.yml", "docusaurus.config.*", "sidebars.*"],
  "ignore": ["site/**", "docs/.vitepress/dist/**", "docs/reports/archive/**"],
  "priorityFiles": ["README.md", "ARCHITECTURE.md", "AI_NAVIGATION.md"],
  "securitySensitivePatterns": [],
  "defaultCompression": false,
  "defaultTokenBudget": 80000,
  "notes": []
}
EOF

write_profile mixed-monorepo <<'EOF'
{
  "id": "mixed-monorepo",
  "displayName": "Mixed Monorepo",
  "description": "Multi-language or workspace repositories.",
  "detect": {"anyFiles": ["pnpm-workspace.yaml", "go.work", "Cargo.toml", "*.sln", "settings.gradle"], "anyDirectories": ["packages", "apps", "services", "crates"]},
  "include": ["README.md", "AGENTS.md", "ARCHITECTURE.md", "AI_NAVIGATION.md", "context-map.yaml", "CHANGELOG.md", "package.json", "pnpm-workspace.yaml", "go.work", "Cargo.toml", "*.sln", "settings.gradle*", "packages/*/package.json", "apps/*/package.json", "services/*/pyproject.toml", "crates/*/Cargo.toml"],
  "ignore": ["**/node_modules/**", "**/.venv/**", "**/target/**", "**/dist/**", "**/build/**", "**/bin/**", "**/obj/**"],
  "priorityFiles": ["ARCHITECTURE.md", "AI_NAVIGATION.md", "package.json", "pnpm-workspace.yaml", "go.work", "Cargo.toml"],
  "securitySensitivePatterns": ["**/.env*", "**/secrets/**", "**/credentials/**"],
  "defaultCompression": true,
  "defaultTokenBudget": 80000,
  "notes": ["Prefer package-level scopes. Do not automatically pack every implementation package."]
}
EOF

write_profile justfile <<'EOF'
{
  "id": "justfile",
  "displayName": "Justfile",
  "description": "Projects using just as a task runner (justfile or Justfile).",
  "detect": {"anyFiles": ["justfile", "Justfile", ".justfile"], "anyDirectories": []},
  "include": ["justfile", "Justfile", ".justfile", "README.md", "AGENTS.md", "ARCHITECTURE.md", "AI_NAVIGATION.md", "context-map.yaml", "CHANGELOG.md"],
  "ignore": [".ai-context/**", "**/.env", "**/.env.*", "**/*.pem", "**/*.key", "**/*.db", "**/*.sqlite", "**/node_modules/**", "**/.venv/**", "**/dist/**", "**/build/**", "**/logs/**", "**/runtime/**", "**/cache/**"],
  "priorityFiles": ["justfile", "Justfile", ".justfile"],
  "securitySensitivePatterns": ["**/.env*", "**/*.pem", "**/*.key"],
  "defaultCompression": false,
  "defaultTokenBudget": 60000,
  "notes": ["Combine with a language-specific profile when the project also has source code."]
}
EOF

write_profile bash <<'EOF'
{
  "id": "bash",
  "displayName": "Bash and Shell",
  "description": "All Bash and shell scripting: application libraries, BATS tests, ShellCheck configuration, deployment scripts, Docker, systemd, and Makefiles. Narrow scope at runtime with --include when only one context is relevant.",
  "detect": {"anyFiles": ["Makefile", "Dockerfile", "docker-compose.yml", "docker-compose.yaml", ".bashrc", ".bash_profile", ".bash_aliases", ".bash_functions", ".shellcheckrc"], "anyDirectories": ["lib", "functions", "bats", "systemd", "deploy", "ops", "infra"]},
  "include": ["**/*.sh", "**/*.bash", "**/*.zsh", "**/*.bats", ".bashrc", ".bash_profile", ".bash_aliases", ".bash_functions", ".shellcheckrc", "bin/**", "lib/**", "functions/**", "tests/**", "deploy/**", "ops/**", "infra/**", "scripts/**", "Makefile", "Dockerfile*", "compose*.yaml", "compose*.yml", ".dockerignore", "systemd/**/*.service", "systemd/**/*.timer", "systemd/**/*.socket", "config/**/*.conf", "config/**/*.cfg", "README.md", "AGENTS.md", "ARCHITECTURE.md", "AI_NAVIGATION.md", "CHANGELOG.md"],
  "ignore": [".ai-context/**", "**/.env", "**/.env.*", "**/*.pem", "**/*.key", "**/node_modules/**", "**/logs/**", "**/runtime/**", "**/cache/**", "**/tmp/**"],
  "priorityFiles": [".shellcheckrc", "Makefile", "Dockerfile*", ".bashrc", ".bash_profile", "lib/**", "functions/**"],
  "securitySensitivePatterns": ["**/.env*", "**/*.pem", "**/*.key", "**/credentials*", "**/secrets*"],
  "defaultCompression": false,
  "defaultTokenBudget": 90000,
  "notes": [
    "Covers all shell scripting: Bash libraries, BATS tests, ShellCheck config, deployment scripts, Docker, systemd, and Makefiles.",
    "Narrow at runtime with --include when only one context is needed (e.g. --include 'systemd/**' for systemd-only work).",
    "Exclude test fixture files that may contain sample credentials."
  ]
}
EOF

write_file "$TARGET_DIR/docs/profile-schema.md" <<'EOF'
# Profile Schema

Each profile is JSON with these fields:

- `id`: unique machine identifier
- `displayName`: human-readable name
- `description`: profile purpose
- `detect.anyFiles`: manifest or marker files
- `detect.anyDirectories`: marker directories
- `include`: default Repomix include patterns
- `ignore`: default ignore patterns
- `priorityFiles`: files that should be read first
- `securitySensitivePatterns`: sensitive paths requiring exclusion
- `defaultCompression`: default compression state
- `defaultTokenBudget`: default token budget
- `notes`: operational notes
EOF

write_file "$TARGET_DIR/docs/repomix-cli-compatibility.md" <<'EOF'
# Repomix CLI Compatibility

Always check:

```bash
repomix --version
repomix --help
```

or:

```bash
npx --yes repomix --version
npx --yes repomix --help
```

Validate required options before use:

- `--config`
- `--style`
- `--include`
- `--ignore`
- `--compress`
- `--include-diffs`
- `--token-budget`
- `--token-count-tree`
- `--mcp`
- `--remote`
- `--remote-branch`

Never silently weaken security or reproducibility when a flag is unavailable.
EOF

write_file "$TARGET_DIR/docs/integration-guide.md" <<'EOF'
# Integration Guide

1. Run `scripts/detect-language-profile`.
2. Review the selected profile.
3. Run `scripts/install-skill-into-project --project PATH --auto-profile --with-config --with-ignore --with-instruction --with-wrappers --with-policy`.
4. Review generated files before commit.
5. Run a conservative smoke pack.
6. Confirm `.ai-context/` is Git-ignored.
EOF

write_file "$TARGET_DIR/docs/troubleshooting.md" <<'EOF'
# Troubleshooting

## Repomix missing

Install or invoke Repomix separately. The skill never installs it automatically.

## Output too large

- narrow `--include`
- select a smaller subsystem
- enable compression for architecture-only work
- reduce token budget
- split the task

## Secrets detected

Stop. Add the source path to `.repomixignore`, remove the generated pack, and regenerate.

## Profile mismatch

Run:

```bash
scripts/detect-language-profile --explain
```

Then pass `--profile` explicitly.
EOF

for f in context-scoping token-budgeting compression-policy security-and-secret-handling static-pack-vs-mcp external-reference-repositories current-vs-historical-authority language-profile-selection; do
  case "$f" in
    context-scoping)
      content='# Context Scoping

## Scoping Flow

```text
task
-> authority files
-> subsystem
-> language profile
-> include patterns
-> exclusions
-> token inspection
-> threshold decision
-> generate
-> validate
-> narrow and retry if required (maximum three attempts)
-> split or abort
-> report
```

Whole-repository packing is exceptional.

## Narrowing Order

When a pack is too large, remove content in this order:

1. Generated, archived, and historical files.
2. Examples, fixtures, and unrelated test files.
3. Broad documentation not directly relevant to the task.
4. Unrelated language ecosystems in mixed-repository packs.
5. Non-essential dependency lock files.

Authoritative governance files must not be removed.'
      ;;
    token-budgeting)
      content='# Token Budgeting

## Workflow Starting Budgets

| Workflow | Starting budget |
|---|---:|
| Small change | 20,000-50,000 |
| Code review | 50,000-100,000 |
| Project onboarding | 80,000-150,000 |
| Architecture review | 100,000-180,000 |
| Local LLM | 20,000-80,000 |
| Remote reference | 50,000-120,000 |

Model context size is not the same as an appropriate Repomix budget.

## Utilisation Thresholds

Budget utilisation = actual or estimated tokens / selected profile token budget x 100.

| Budget utilisation | Required action |
|---|---|
| 0-60% | Continue with the selected scope |
| 61-80% | Continue, but remove non-essential examples, broad documentation, and unrelated tests where safe |
| 81-100% | Narrow the pack to the directly relevant subsystem before final generation |
| Above 100% | Do not deliver the pack; execute the retry strategy |
| Unknown | Run token inspection or generate a narrowly scoped diagnostic pack first |

## Retry Behaviour

When utilisation exceeds 100%:

1. Remove generated, archived, historical, example, fixture, and unrelated test content.
2. Restrict scope to the affected package, service, module, or subsystem.
3. Retain governance files and directly relevant dependency manifests.
4. Remove unrelated language ecosystems from mixed-repository profiles.
5. Enable compression only when exact implementation bodies are not required.
6. Recalculate or regenerate the pack.
7. Repeat for a maximum of three attempts.
8. If still over budget, split into named logical packs or abort with a report.

## Prohibited Behaviours

- Do not silently truncate output to fit a budget.
- Do not silently deliver a pack that exceeds the token budget.
- Do not remove authoritative governance files to save tokens.
- Do not enable compression solely to satisfy the budget when exact implementation is required.'
      ;;
    compression-policy)
      content='# Compression Policy

Use compression for architecture discovery, external repositories, broad structural review, and constrained local models.

Do not use compression for debugging, SQL correctness, financial logic, validation code, exact configuration semantics, error handling, authentication, or authorisation.

## Budget and Truncation Rules

- Compression MUST NOT be used solely to satisfy the token budget.
- When exact implementation logic is required, narrow the scope first; do not compress.
- Compression decisions must be recorded in the run report under Compression justification.
- Do not silently compress output when full source was requested or required.'
      ;;
    security-and-secret-handling)
      content='# Security and Secret Handling

Order:

1. exclude secrets
2. run security scanning
3. manually inspect output
4. upload externally only after review

Security scanning is defence-in-depth, not proof of safety.'
      ;;
    static-pack-vs-mcp)
      content='# Static Pack vs MCP

Use MCP for dynamic exploration and unknown file scope.

Use static packs for reproducible audits, fixed evidence, human review, and local LLM input.

## Ambiguous Routing

When more than one route is valid:

1. Prefer the route with the smallest safe context footprint.
2. Prefer static output when reproducibility is required.
3. Prefer MCP when scope is unknown and interactive discovery is available.
4. Prefer full source over compression when implementation correctness matters.
5. Prefer project-specific governance over skill defaults.
6. If ambiguity materially affects safety, cost, privacy, or correctness, ask the user.
7. Otherwise, choose the safest route and record the decision.

## Escalation Authority

The user or project owner is the escalation authority for unresolved routing decisions. The skill must not invent an additional approval authority.'
      ;;
    external-reference-repositories)
      content='# External Reference Repositories

- pin a tag, branch, or commit
- do not trust remote Repomix configuration
- use compression by default
- scope to the relevant subsystem
- record the revision used'
      ;;
    current-vs-historical-authority)
      # shellcheck disable=SC2016
      content='# Current vs Historical Authority

- `CURRENT AUTHORITATIVE`: current truth
- `CURRENT SUPPORTING`: supporting evidence
- `SUPERSEDED`: not current truth
- `HISTORICAL BASELINE`: past state
- `HISTORICAL IMPLEMENTATION`: implementation history
- `ARCHIVE / LOG`: forensic evidence
- `GENERATED`: derived output

Do not infer current state from superseded or historical files.'
      ;;
    language-profile-selection)
      content='# Language Profile Selection

Use auto-detection as a recommendation, not an unquestioned decision.

For monorepos, select a package or subsystem before combining profiles.

Use explicit overrides when repository structure is unconventional.'
      ;;
  esac
  write_file "$TARGET_DIR/patterns/$f.md" <<<"$content"
done

write_file "$TARGET_DIR/examples/codex-current-state.md" <<'EOF'
# codex current state

## Scenario

Pack the current repository state as a structured context snapshot for Codex or another agent.

## Command

```bash
scripts/repomix-current --repo .
```

## Variants

```bash
# Narrow to a subsystem
scripts/repomix-current --repo . --include "src/api/**"

# Override profile and token budget
scripts/repomix-current --repo . --profile python --token-budget 80000

# Force overwrite of existing output
scripts/repomix-current --repo . --force
```

## Output

`.ai-context/current-state.xml`

## Guidance

Auto-detects the repository language profile. Use `--include` to narrow scope when only one subsystem is needed. Keep security scanning enabled. Do not use `--no-security-check`.
EOF

write_file "$TARGET_DIR/examples/claude-code-review.md" <<'EOF'
# claude code review

## Scenario

Pack the repository with diffs included for a Claude code review session.

## Command

```bash
scripts/claude-repomix-review --repo .
```

## Variants

```bash
# Markdown output for direct paste into a chat
scripts/claude-repomix-review --repo . --style markdown

# Custom output path
scripts/claude-repomix-review --repo . --output .ai-context/my-review.md

# Narrow to changed subsystem only
scripts/claude-repomix-review --repo . --include "src/auth/**"
```

## Output

`.ai-context/claude-review.md`

## Guidance

Always includes `--include-diffs`. Select the smallest relevant profile and scope. Review the generated output before sharing with Claude.
EOF

write_file "$TARGET_DIR/examples/local-llm-compressed-pack.md" <<'EOF'
# local llm compressed pack

## Scenario

Pack a repository with aggressive compression for a local LLM with a tight context window.

## Command

```bash
scripts/repomix-current --repo . --compress --token-budget 32000
```

## Variants

```bash
# Python project, compressed, very tight budget
scripts/repomix-current --repo . --profile python --compress --token-budget 20000

# Narrow to core source only, exclude tests
scripts/repomix-current --repo . --compress --token-budget 32000 \
  --include "src/**" --ignore "tests/**,docs/**"
```

## Output

`.ai-context/current-state.xml`

## Guidance

Compression strips comments and whitespace. Use `--include` to reduce scope before relying on compression alone. Do not compress implementation-sensitive code merely to make it fit — split the task instead if budget is exceeded after 3 attempts.
EOF

write_file "$TARGET_DIR/examples/remote-foss-reference.md" <<'EOF'
# remote foss reference

## Scenario

Pack a pinned remote open-source repository as a reusable reference pack for architecture comparison or API research.

## Command

```bash
scripts/repomix-reference --repo . owner/repo --revision v1.2.3
```

## Variants

```bash
# Allow default branch (not recommended; use only for rapid exploration)
scripts/repomix-reference --repo . owner/repo --allow-default-branch

# Custom output path
scripts/repomix-reference --repo . owner/repo --revision v2.0.0 \
  --output .ai-context/references/mylib-v2.xml
```

## Output

`.ai-context/references/<remote>-<revision>.xml`

## Guidance

A pinned `--revision` is required by default to ensure reproducible reference packs. Use `--allow-default-branch` only for exploratory work, never for durable references.
EOF

write_file "$TARGET_DIR/examples/security-review.md" <<'EOF'
# security review

## Scenario

Pack the repository for a focused security review, scoping to source code and configuration while excluding secrets, credentials, and runtime state.

## Command

```bash
scripts/repomix-security --repo .
```

## Variants

```bash
# Narrow to authentication and configuration only
scripts/repomix-security --repo . --include "src/auth/**,config/**"

# Custom output
scripts/repomix-security --repo . --output .ai-context/security-review.xml
```

## Output

`.ai-context/security-review.xml`

## Guidance

Security exclusions (`.env`, credentials, keys, databases, logs) are always applied. Do not pass `--no-security-check` — it is prohibited. Review the pack before sharing to confirm no sensitive data was captured.
EOF

write_file "$TARGET_DIR/examples/mixed-monorepo.md" <<'EOF'
# mixed monorepo

## Scenario

Pack a single service or subsystem from a mixed-language monorepo without pulling in unrelated packages.

## Command

```bash
# Pack one service with its profile auto-detected
scripts/repomix-current --repo . --include "services/auth/**"
```

## Variants

```bash
# Pack a Go service with explicit profile
scripts/repomix-current --repo . --profile go --include "services/payments/**"

# Pack the shared infrastructure layer
scripts/repomix-current --repo . --profile ansible --include "infra/**"

# Pack frontend only from a full-stack monorepo
scripts/repomix-current --repo . --profile javascript-typescript \
  --include "apps/web/**,packages/ui/**"
```

## Output

`.ai-context/current-state.xml`

## Guidance

Always use `--include` to scope to one service or package. The `mixed-monorepo` profile is for architecture discovery across the whole repo — use a language-specific profile when focusing on a single service. Combine profiles with `--include` rather than removing exclusions.
EOF

# Shared wrapper library
write_file "$TARGET_DIR/scripts/_repomix-common.sh" 0755 <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

find_repo_root() {
  local start="${1:-$PWD}"
  if git -C "$start" rev-parse --show-toplevel >/dev/null 2>&1; then
    git -C "$start" rev-parse --show-toplevel
  else
    (cd "$start" && pwd)
  fi
}

repomix_cmd() {
  if command -v repomix >/dev/null 2>&1; then
    printf '%s\n' "repomix"
  elif command -v npx >/dev/null 2>&1; then
    printf '%s\n' "npx --yes repomix"
  else
    die "Repomix not found. Install Repomix or make npx available."
  fi
}

assert_safe_repo() {
  local repo="$1"
  [[ "$repo" != "/" ]] || die "Refusing repository root /"
  [[ "$repo" != "$HOME" ]] || die "Refusing repository root \$HOME"
}

assert_safe_output() {
  local repo="$1"
  local output="$2"
  case "$output" in
    "$repo"/.ai-context/*|.ai-context/*) ;;
    *) die "Output must remain under .ai-context/: $output" ;;
  esac
}

join_csv() {
  local IFS=,
  printf '%s' "$*"
}
EOF

write_file "$TARGET_DIR/scripts/detect-language-profile" 0755 <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

REPO="$PWD"
JSON=0
PRIMARY_ONLY=0
EXPLAIN=0

usage() {
  cat <<'USAGE'
Usage: detect-language-profile [--repo PATH] [--json] [--primary-only] [--explain]
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2 ;;
    --json) JSON=1; shift ;;
    --primary-only) PRIMARY_ONLY=1; shift ;;
    --explain) EXPLAIN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; exit 2 ;;
  esac
done

REPO="$(cd "$REPO" && pwd)"
profiles=()
evidence=()

add_profile() {
  local p="$1" e="$2"
  profiles+=("$p")
  evidence+=("$e")
}

[[ -f "$REPO/pyproject.toml" || -f "$REPO/setup.py" || -f "$REPO/requirements.txt" ]] && add_profile python "python manifest"
[[ -f "$REPO/package.json" ]] && add_profile javascript-typescript "package.json"
[[ -f "$REPO/go.mod" || -f "$REPO/go.work" ]] && add_profile go "go manifest"
[[ -f "$REPO/Cargo.toml" ]] && add_profile rust "Cargo.toml"
[[ -f "$REPO/pom.xml" || -f "$REPO/build.gradle" || -f "$REPO/build.gradle.kts" ]] && add_profile java-kotlin "JVM build file"
compgen -G "$REPO/*.sln" >/dev/null && add_profile dotnet ".sln"
[[ -f "$REPO/Gemfile" ]] && add_profile ruby "Gemfile"
[[ -f "$REPO/composer.json" ]] && add_profile php "composer.json"
[[ -f "$REPO/ansible.cfg" || -d "$REPO/roles" || -d "$REPO/playbooks" ]] && add_profile ansible "Ansible structure"
find "$REPO" -maxdepth 2 -name '*.tf' -print -quit 2>/dev/null | grep -q . && add_profile terraform "*.tf"
[[ -f "$REPO/dbt_project.yml" || -d "$REPO/sql" || -d "$REPO/models" ]] && add_profile data-sql "data/SQL structure"
[[ -d "$REPO/docs" ]] && add_profile documentation "docs/"
find "$REPO" -maxdepth 2 \( -name '*.sh' -o -name 'Dockerfile' -o -name 'Makefile' \) -print -quit 2>/dev/null | grep -q . && add_profile bash "shell, Docker, or Makefile"

count="${#profiles[@]}"
if [[ "$count" -eq 0 ]]; then
  primary="base"
  secondary=""
  repo_type="unknown"
  recommended="base"
  confidence="low"
elif [[ "$count" -eq 1 ]]; then
  primary="${profiles[0]}"
  secondary=""
  repo_type="single"
  recommended="$primary"
  confidence="high"
else
  primary="${profiles[0]}"
  secondary="$(IFS=,; echo "${profiles[*]:1}")"
  repo_type="mixed"
  recommended="mixed-monorepo"
  confidence="high"
fi

if [[ "$PRIMARY_ONLY" -eq 1 ]]; then
  printf '%s\n' "$primary"
  exit 0
fi

if [[ "$JSON" -eq 1 ]]; then
  esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
  printf '{\n'
  printf '  "primary": "%s",\n' "$(esc "$primary")"
  printf '  "secondary": ['
  if [[ -n "$secondary" ]]; then
    IFS=',' read -r -a sec <<<"$secondary"
    for i in "${!sec[@]}"; do
      [[ "$i" -gt 0 ]] && printf ', '
      printf '"%s"' "$(esc "${sec[$i]}")"
    done
  fi
  printf '],\n'
  printf '  "repositoryType": "%s",\n' "$repo_type"
  printf '  "recommendedProfile": "%s",\n' "$recommended"
  printf '  "confidence": "%s",\n' "$confidence"
  printf '  "evidence": ['
  for i in "${!evidence[@]}"; do
    [[ "$i" -gt 0 ]] && printf ', '
    printf '"%s"' "$(esc "${evidence[$i]}")"
  done
  printf ']\n}\n'
else
  printf 'primary=%s\n' "$primary"
  printf 'secondary=%s\n' "$secondary"
  printf 'repository_type=%s\n' "$repo_type"
  printf 'recommended_profile=%s\n' "$recommended"
  printf 'confidence=%s\n' "$confidence"
  if [[ "$EXPLAIN" -eq 1 ]]; then
    printf 'evidence=%s\n' "$(IFS=';'; echo "${evidence[*]}")"
  fi
fi
EOF

# Wrapper generator
make_wrapper() {
  local name="$1" mode="$2" output="$3" compress_default="$4"
  write_file "$TARGET_DIR/scripts/$name" 0755 <<EOF
#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_repomix-common.sh
source "\$SCRIPT_DIR/_repomix-common.sh"

REPO="\$PWD"
PROFILE="auto"
OUTPUT="$output"
INCLUDE=""
IGNORE=""
TOKEN_BUDGET=""
COMPRESS=$compress_default
WITH_LOGS=0
LOG_COUNT=10
REMOTE=""
REVISION=""
ALLOW_DEFAULT=0
FORCE=0
STYLE="xml"

usage() {
  cat <<'USAGE'
Usage: $name [options]
  --repo PATH
  --profile PROFILE
  --include PATTERNS
  --ignore PATTERNS
  --output PATH
  --token-budget NUMBER
  --compress
  --no-compress
  --with-logs
  --log-count NUMBER
  --revision VALUE
  --allow-default-branch
  --style xml|markdown|json|plain
  --force
USAGE
}

# shellcheck disable=SC2050,SC2194
if [[ "$mode" == "reference" ]]; then
  [[ \$# -gt 0 ]] || { usage; exit 2; }
  REMOTE="\$1"
  shift
fi

while [[ \$# -gt 0 ]]; do
  case "\$1" in
    --repo) REPO="\$2"; shift 2 ;;
    --profile) PROFILE="\$2"; shift 2 ;;
    --include) INCLUDE="\$2"; shift 2 ;;
    --ignore) IGNORE="\$2"; shift 2 ;;
    --output) OUTPUT="\$2"; shift 2 ;;
    --token-budget) TOKEN_BUDGET="\$2"; shift 2 ;;
    --compress) COMPRESS=1; shift ;;
    --no-compress) COMPRESS=0; shift ;;
    --with-logs) WITH_LOGS=1; shift ;;
    --log-count) LOG_COUNT="\$2"; shift 2 ;;
    --revision) REVISION="\$2"; shift 2 ;;
    --allow-default-branch) ALLOW_DEFAULT=1; shift ;;
    --style) STYLE="\$2"; shift 2 ;;
    --force) FORCE=1; shift ;;
    --no-security-check) die "--no-security-check is prohibited" ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown option: \$1" ;;
  esac
done

REPO="\$(find_repo_root "\$REPO")"
assert_safe_repo "\$REPO"

if [[ "\$PROFILE" == "auto" ]]; then
  PROFILE="\$("\$SCRIPT_DIR/detect-language-profile" --repo "\$REPO" --primary-only)"
fi

# shellcheck disable=SC2050,SC2194
if [[ "$mode" == "reference" ]]; then
  if [[ -z "\$REVISION" && "\$ALLOW_DEFAULT" -ne 1 ]]; then
    die "A pinned --revision is required"
  fi
  safe_remote="\$(printf '%s' "\$REMOTE" | sed 's#https\?://##; s#[^A-Za-z0-9._-]#-#g')"
  safe_revision="\$(printf '%s' "\${REVISION:-default}" | sed 's#[^A-Za-z0-9._-]#-#g')"
  if [[ "\$OUTPUT" == "$output" ]]; then
    OUTPUT=".ai-context/references/\${safe_remote}-\${safe_revision}.xml"
  fi
fi

if [[ "\$OUTPUT" != /* ]]; then
  OUTPUT="\$REPO/\$OUTPUT"
fi
assert_safe_output "\$REPO" "\$OUTPUT"
mkdir -p "\$(dirname "\$OUTPUT")"
[[ ! -e "\$OUTPUT" || "\$FORCE" -eq 1 ]] || die "Output exists; use --force: \$OUTPUT"

read -r -a RBASE <<<"\$(repomix_cmd)"
cmd=("\${RBASE[@]}" --style "\$STYLE" --output "\$OUTPUT")

[[ -n "\$INCLUDE" ]] && cmd+=(--include "\$INCLUDE")
[[ -n "\$IGNORE" ]] && cmd+=(--ignore "\$IGNORE")
[[ -n "\$TOKEN_BUDGET" ]] && cmd+=(--token-budget "\$TOKEN_BUDGET")
[[ "\$COMPRESS" -eq 1 ]] && cmd+=(--compress)

# shellcheck disable=SC2050,SC2194
case "$mode" in
  review)
    cmd+=(--include-diffs)
    if [[ "\$WITH_LOGS" -eq 1 ]]; then
      cmd+=(--include-logs --include-logs-count "\$LOG_COUNT")
    fi
    ;;
  reference)
    cmd+=(--remote "\$REMOTE")
    [[ -n "\$REVISION" ]] && cmd+=(--remote-branch "\$REVISION")
    ;;
esac

printf 'Profile: %s\n' "\$PROFILE"
printf 'Output: %s\n' "\$OUTPUT"
printf 'Command:'
printf ' %q' "\${cmd[@]}"
printf '\n'
(cd "\$REPO" && "\${cmd[@]}")
EOF
}

make_wrapper repomix-current current ".ai-context/current-state.xml" 0
make_wrapper repomix-review review ".ai-context/change-review.xml" 0
make_wrapper repomix-security security ".ai-context/security-review.xml" 0
make_wrapper repomix-reference reference ".ai-context/references/reference.xml" 1

write_file "$TARGET_DIR/scripts/claude-repomix-review" 0755 <<'EOF'
#!/usr/bin/env bash
# Change-review pack optimised for Claude Code: Markdown output with diffs included.
set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_repomix-common.sh
source "$SCRIPT_DIR/_repomix-common.sh"

REPO="$PWD"
PROFILE="auto"
OUTPUT=".ai-context/claude-review.md"
INCLUDE=""
IGNORE=""
TOKEN_BUDGET=""
COMPRESS=0
WITH_LOGS=0
LOG_COUNT=10
STYLE="markdown"
FORCE=0

usage() {
  cat <<'USAGE'
Usage: claude-repomix-review [options]
  --repo PATH
  --profile PROFILE
  --include PATTERNS
  --ignore PATTERNS
  --output PATH
  --token-budget NUMBER
  --compress
  --no-compress
  --with-logs
  --log-count NUMBER
  --style markdown|xml|json|plain
  --force
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)          REPO="$2";          shift 2 ;;
    --profile)       PROFILE="$2";       shift 2 ;;
    --include)       INCLUDE="$2";       shift 2 ;;
    --ignore)        IGNORE="$2";        shift 2 ;;
    --output)        OUTPUT="$2";        shift 2 ;;
    --token-budget)  TOKEN_BUDGET="$2";  shift 2 ;;
    --compress)      COMPRESS=1;         shift ;;
    --no-compress)   COMPRESS=0;         shift ;;
    --with-logs)     WITH_LOGS=1;        shift ;;
    --log-count)     LOG_COUNT="$2";     shift 2 ;;
    --style)         STYLE="$2";         shift 2 ;;
    --force)         FORCE=1;            shift ;;
    --no-security-check) die "--no-security-check is prohibited" ;;
    -h|--help)       usage; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

REPO="$(find_repo_root "$REPO")"
assert_safe_repo "$REPO"

if [[ "$PROFILE" == "auto" ]]; then
  PROFILE="$("$SCRIPT_DIR/detect-language-profile" --repo "$REPO" --primary-only)"
fi

if [[ "$OUTPUT" != /* ]]; then
  OUTPUT="$REPO/$OUTPUT"
fi
assert_safe_output "$REPO" "$OUTPUT"
mkdir -p "$(dirname "$OUTPUT")"
[[ ! -e "$OUTPUT" || "$FORCE" -eq 1 ]] || die "Output exists; use --force: $OUTPUT"

read -r -a RBASE <<<"$(repomix_cmd)"
cmd=("${RBASE[@]}" --style "$STYLE" --output "$OUTPUT" --include-diffs)

[[ -n "$INCLUDE" ]]       && cmd+=(--include "$INCLUDE")
[[ -n "$IGNORE" ]]        && cmd+=(--ignore "$IGNORE")
[[ -n "$TOKEN_BUDGET" ]]  && cmd+=(--token-budget "$TOKEN_BUDGET")
[[ "$COMPRESS" -eq 1 ]]   && cmd+=(--compress)
[[ "$WITH_LOGS" -eq 1 ]]  && cmd+=(--include-logs --include-logs-count "$LOG_COUNT")

printf 'Profile: %s\n' "$PROFILE"
printf 'Style:   %s\n' "$STYLE"
printf 'Output:  %s\n' "$OUTPUT"
printf 'Command:'
printf ' %q' "${cmd[@]}"
printf '\n'
(cd "$REPO" && "${cmd[@]}")
EOF

write_file "$TARGET_DIR/scripts/install-skill-into-project" 0755 <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT=""
PROFILE=""
AUTO=0
WITH_WRAPPERS=0
WITH_POLICY=0
WITH_CONFIG=0
WITH_IGNORE=0
WITH_INSTRUCTION=0
FORCE=0
DRY_RUN=0

usage() {
  cat <<'USAGE'
Usage: install-skill-into-project --project PATH [options]
  --profile PROFILE
  --auto-profile
  --with-wrappers
  --with-policy
  --with-config
  --with-ignore
  --with-instruction
  --force
  --dry-run
USAGE
}

copy_one() {
  local src="$1" dst="$2"
  if [[ -e "$dst" && "$FORCE" -ne 1 ]]; then
    printf 'SKIP existing: %s\n' "$dst"
    return
  fi
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf 'WOULD COPY: %s -> %s\n' "$src" "$dst"
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project) PROJECT="$2"; shift 2 ;;
    --profile) PROFILE="$2"; shift 2 ;;
    --auto-profile) AUTO=1; shift ;;
    --with-wrappers) WITH_WRAPPERS=1; shift ;;
    --with-policy) WITH_POLICY=1; shift ;;
    --with-config) WITH_CONFIG=1; shift ;;
    --with-ignore) WITH_IGNORE=1; shift ;;
    --with-instruction) WITH_INSTRUCTION=1; shift ;;
    --force) FORCE=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; exit 2 ;;
  esac
done

[[ -n "$PROJECT" ]] || { usage; exit 2; }
PROJECT="$(cd "$PROJECT" && pwd)"

if [[ "$AUTO" -eq 1 ]]; then
  PROFILE="$("$SCRIPT_DIR/detect-language-profile" --repo "$PROJECT" --primary-only)"
fi
printf 'Selected profile: %s\n' "${PROFILE:-base}"

[[ "$WITH_CONFIG" -eq 1 ]] && copy_one "$ROOT/templates/repomix.config.json" "$PROJECT/repomix.config.json"
[[ "$WITH_IGNORE" -eq 1 ]] && copy_one "$ROOT/templates/.repomixignore" "$PROJECT/.repomixignore"
[[ "$WITH_INSTRUCTION" -eq 1 ]] && copy_one "$ROOT/templates/repomix-instruction.md" "$PROJECT/repomix-instruction.md"
[[ "$WITH_POLICY" -eq 1 ]] && copy_one "$ROOT/templates/repomix-mcp-routing-policy.md" "$PROJECT/docs/policies/repomix-mcp-routing-policy.md"

if [[ "$WITH_WRAPPERS" -eq 1 ]]; then
  for f in repomix-current repomix-review repomix-security repomix-reference detect-language-profile _repomix-common.sh; do
    copy_one "$ROOT/scripts/$f" "$PROJECT/scripts/$f"
    [[ "$DRY_RUN" -eq 1 ]] || chmod +x "$PROJECT/scripts/$f"
  done
fi
EOF

write_file "$TARGET_DIR/scripts/validate-skill.sh" 0755 <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fail=0

required=(
  SKILL.md README.md AGENTS.md ARCHITECTURE.md AI_NAVIGATION.md
  context-map.yaml CHANGELOG.md
  templates/repomix.config.json templates/.repomixignore
  templates/repomix-instruction.md templates/repomix-mcp-routing-policy.md
  scripts/repomix-current scripts/repomix-review scripts/repomix-security
  scripts/repomix-reference scripts/detect-language-profile
  scripts/install-skill-into-project
)

for f in "${required[@]}"; do
  [[ -e "$ROOT/$f" ]] || { printf 'Missing: %s\n' "$f"; fail=1; }
done

for f in "$ROOT"/scripts/*; do
  [[ -f "$f" ]] || continue
  bash -n "$f" || fail=1
done

if command -v python3 >/dev/null 2>&1; then
  for f in "$ROOT"/profiles/*.json "$ROOT/templates/repomix.config.json"; do
    python3 -m json.tool "$f" >/dev/null || fail=1
  done
fi

grep -q '^name: skill-repomix' "$ROOT/SKILL.md" || { printf 'Missing name frontmatter in SKILL.md\n'; fail=1; }
grep -q '\.ai-context/' "$ROOT/templates/.repomixignore" || { printf 'Missing .ai-context/ in .repomixignore\n'; fail=1; }

if grep -R -- '--no-security-check' "$ROOT/scripts" | grep -v 'prohibited' >/dev/null 2>&1; then
  printf 'Forbidden security-disable support detected\n'
  fail=1
fi

# Behavioural contract section checks
check_phrase() {
  local file="$1" phrase="$2"
  grep -qF "$phrase" "$ROOT/$file" || { printf 'Missing in %s: %s\n' "$file" "$phrase"; fail=1; }
}

check_phrase SKILL.md '## Audience and Authority'
check_phrase SKILL.md '## Token-Budget Thresholds'
check_phrase SKILL.md '## Pack-Too-Large Retry Strategy'
check_phrase SKILL.md '## Ambiguous Routing'
check_phrase SKILL.md '## Required Run Report'
check_phrase SKILL.md 'maximum of three attempts'
check_phrase SKILL.md 'silently truncate'
check_phrase SKILL.md 'Repomix Execution Summary'
check_phrase SKILL.md 'Compression justification'
check_phrase SKILL.md 'Budget utilisation'
check_phrase SKILL.md 'Retry attempts'

check_phrase README.md '## Audience'

check_phrase context-map.yaml 'agent_behavior'
check_phrase context-map.yaml 'human_operations'
check_phrase context-map.yaml 'token_policy'

check_phrase patterns/token-budgeting.md 'maximum of three attempts'
check_phrase patterns/token-budgeting.md 'silently truncate'
check_phrase patterns/token-budgeting.md 'Budget utilisation'

check_phrase patterns/context-scoping.md 'split or abort'

check_phrase patterns/static-pack-vs-mcp.md 'escalation authority'

check_phrase AGENTS.md 'synchronised between'

if command -v shellcheck >/dev/null 2>&1; then
  for f in "$ROOT"/scripts/*; do
    [[ -f "$f" ]] || continue
    shellcheck -x -S warning "$f" || fail=1
  done
else
  printf 'ShellCheck not available — not checked\n'
fi

if [[ "$fail" -ne 0 ]]; then
  printf 'Validation failed\n'
  exit 1
fi

printf 'Validation passed\n'
EOF

# fixtures
write_file "$TARGET_DIR/tests/fixtures/python-project/pyproject.toml" <<'EOF'
[project]
name = "fixture"
version = "0.1.0"
EOF
write_file "$TARGET_DIR/tests/fixtures/python-project/src/app.py" <<'EOF'
print("fixture")
EOF
write_file "$TARGET_DIR/tests/fixtures/typescript-project/package.json" <<'EOF'
{"name":"fixture","version":"0.1.0"}
EOF
write_file "$TARGET_DIR/tests/fixtures/typescript-project/src/index.ts" <<'EOF'
export const fixture = true;
EOF
write_file "$TARGET_DIR/tests/fixtures/mixed-project/pyproject.toml" <<'EOF'
[project]
name = "fixture"
version = "0.1.0"
EOF
write_file "$TARGET_DIR/tests/fixtures/mixed-project/package.json" <<'EOF'
{"name":"fixture","version":"0.1.0"}
EOF

write_file "$TARGET_DIR/tests/test-skill-repomix.sh" 0755 <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

"$ROOT/scripts/validate-skill.sh"

[[ "$("$ROOT/scripts/detect-language-profile" --repo "$ROOT/tests/fixtures/python-project" --primary-only)" == "python" ]]
[[ "$("$ROOT/scripts/detect-language-profile" --repo "$ROOT/tests/fixtures/typescript-project" --primary-only)" == "javascript-typescript" ]]
[[ "$("$ROOT/scripts/detect-language-profile" --repo "$ROOT/tests/fixtures/mixed-project" --json)" == *'"recommendedProfile": "mixed-monorepo"'* ]]

if "$ROOT/scripts/repomix-security" --no-security-check >/dev/null 2>&1; then
  printf 'Security wrapper incorrectly accepted --no-security-check\n'
  exit 1
fi

if "$ROOT/scripts/repomix-reference" owner/repo >/dev/null 2>&1; then
  printf 'Reference wrapper incorrectly allowed missing revision\n'
  exit 1
fi

# Behavioural contract requirement checks
check_heading() {
  local file="$1" heading="$2"
  grep -qF "$heading" "$ROOT/$file" || { printf 'Missing heading in %s: %s\n' "$file" "$heading"; exit 1; }
}

check_phrase() {
  local file="$1" phrase="$2"
  grep -qF "$phrase" "$ROOT/$file" || { printf 'Missing phrase in %s: %s\n' "$file" "$phrase"; exit 1; }
}

check_heading SKILL.md '## Audience and Authority'
check_heading SKILL.md '## Token-Budget Thresholds'
check_heading SKILL.md '## Pack-Too-Large Retry Strategy'
check_heading SKILL.md '## Ambiguous Routing'
check_heading SKILL.md '## Required Run Report'

check_phrase SKILL.md 'maximum of three attempts'
check_phrase SKILL.md 'silently truncate'
check_phrase SKILL.md 'Repomix Execution Summary'
check_phrase SKILL.md 'Compression justification'
check_phrase SKILL.md 'Budget utilisation'
check_phrase SKILL.md 'Retry attempts'

check_phrase README.md '## Audience'

check_phrase context-map.yaml 'agent_behavior'
check_phrase context-map.yaml 'human_operations'
check_phrase context-map.yaml 'token_policy'

check_phrase patterns/token-budgeting.md 'maximum of three attempts'
check_phrase patterns/token-budgeting.md 'silently truncate'

check_phrase patterns/context-scoping.md 'split or abort'

check_phrase patterns/static-pack-vs-mcp.md 'escalation authority'

check_phrase AGENTS.md 'synchronised between'

# Idempotency test: generator output must match current files
GENERATOR="$ROOT/create-skill-repomix.sh"
if [[ -x "$GENERATOR" ]]; then
  GEN_OUT="$TMP/skill-repomix-idempotency"
  "$GENERATOR" --target-dir "$GEN_OUT"
  for f in SKILL.md README.md AGENTS.md AI_NAVIGATION.md context-map.yaml \
            patterns/token-budgeting.md patterns/context-scoping.md \
            patterns/static-pack-vs-mcp.md patterns/compression-policy.md \
            scripts/validate-skill.sh tests/test-skill-repomix.sh; do
    if [[ -f "$ROOT/$f" && -f "$GEN_OUT/$f" ]]; then
      diff -q "$ROOT/$f" "$GEN_OUT/$f" >/dev/null || {
        printf 'Idempotency drift detected: %s\n' "$f"
        exit 1
      }
    fi
  done
  printf 'Idempotency check passed\n'
else
  printf 'SKIP idempotency: generator not found or not executable\n'
fi

printf 'All tests passed\n'
EOF

# verify generated files
if [[ "$DRY_RUN" -eq 0 ]]; then
  "$TARGET_DIR/scripts/validate-skill.sh"
  log "Created skill-repomix at $TARGET_DIR"
  log "Run tests with: $TARGET_DIR/tests/test-skill-repomix.sh"
else
  log "Dry run complete"
fi
