#!/usr/bin/env python3
"""Read every governed file's header in the form native to its type, and list them so a file is assessed without being opened. Stdlib only.

Why (operator, 2026-10-10: "the front matter ... will help in assessing a file rather than reading the whole document"; "make it a standard
for scripts as well as other files like YAML"): an agent decides what to open from a one-line view (status, summary, review date) instead
of reading bodies. This module is the one parser the other skill-ai-it tools import (doc_freshness.py, rotate_records.py), so every tool
reads headers the same way.

Header forms (governance `categories/naming-and-file-summary-guide.md`, "File headers"):
- Markdown: front matter, `---` fenced (or a legacy bare `Key: value` block), keys such as Title, Category, Status, Summary, Last reviewed,
  Review by, Depends on, Superseded by, Budget, Archive.
- Python: the module docstring; its first line is the summary; optional `Key: value` lines inside it (Status, Depends on, Review by).
- YAML, shell, justfile, TOML: the leading `#` comment block; `# Key: value` lines are keys, the first other comment line is the summary.
- JSON: a top-level `_meta` object (keys as above), or a `_note` string as the summary.

Usage:
    python scripts/file_headers.py --project-root . docs/engineering            # one line per file under a folder (just docs)
    python scripts/file_headers.py --project-root . --missing scripts wc-local    # files with no summary, by type
Exit: 0, or 2 on bad arguments.
"""

from __future__ import annotations

import argparse
import ast
import json
import pathlib
import re
import subprocess
import sys

KEYS = ("title", "category", "status", "summary", "last reviewed", "review by", "depends on", "superseded by", "budget", "archive",
        "kind", "generated by", "verified by", "last rotated", "authority", "scope", "description", "keep", "open items tracker", "pinned sections")
KEY_LINE = re.compile(r"^([A-Za-z][A-Za-z ]{1,24}):\s*(.*)$")
COMMENT_TYPES = {".yaml", ".yml", ".sh", ".toml", ".just", ".cfg", ".ini"}
HEADER_TYPES = {".md", ".py", ".json"} | COMMENT_TYPES
#: Folder indexes and convention-locked entry points are routing, not documents; their first heading is their header.
INDEX_NAMES = {"readme.md", "README.md", "CHANGELOG.md", "CLAUDE.md", "__init__.py"}
#: Verbatim or generated material: captures, pulled sources, backups, archives and rendered views carry no header of their own.
SKIP_PARTS = ("-sources-", "/captures/", "/backups/", "/archive/", "/history/", "/node_modules/", "/.venv/", "/vendor-sources/", "/__pycache__/",
              "/migrations/")


def _keys_from_lines(lines: list[str]) -> dict[str, str]:
    """Collect `Key: value` pairs, joining folded (`>-`) values from their indented lines.

    Args:
        lines: candidate header lines with comment markers already removed.

    Returns:
        Lower-cased known keys to values.
    """
    out: dict[str, str] = {}
    i = 0
    while i < len(lines):
        m = KEY_LINE.match(lines[i])
        if m and m.group(1).lower() in KEYS:
            key, val = m.group(1).lower(), m.group(2).strip()
            if val in (">-", ">", "|"):
                parts = []
                while i + 1 < len(lines) and lines[i + 1].startswith((" ", "\t")):
                    i += 1
                    parts.append(lines[i].strip())
                val = " ".join(parts)
            out[key] = val
        i += 1
    if "summary" not in out and out.get("description"):
        out["summary"] = out["description"]
    return out


def read_header(path: pathlib.Path) -> dict[str, str]:
    """A file's header keys, in the form native to its type.

    Args:
        path: the file.

    Returns:
        Lower-cased keys to values; `summary` is filled from the type's summary line when no Summary key is given. Empty when the type
        has no header form or the file cannot be read.
    """
    suffix = ".just" if path.name == "justfile" else path.suffix
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return {}
    if suffix == ".md":
        lines = text.splitlines()[:60]
        if lines and lines[0].strip() == "---":
            end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), len(lines))
            return _keys_from_lines(lines[1:end])
        return _keys_from_lines(lines[:40])
    if suffix == ".py":
        try:
            doc = ast.get_docstring(ast.parse(text)) or ""
        except SyntaxError:
            return {}
        keys = _keys_from_lines(doc.splitlines())
        first = doc.strip().splitlines()[0] if doc.strip() else ""
        if first and "summary" not in keys:
            keys["summary"] = first
        return keys
    if suffix in COMMENT_TYPES:
        block: list[str] = []
        for line in text.splitlines():
            if line.startswith("#!"):
                continue
            if not line.startswith("#"):
                break
            block.append(line.lstrip("#").strip() if not line.startswith("#  ") else "  " + line[3:])
        keys = _keys_from_lines(block)
        first = next((b for b in block if b and not KEY_LINE.match(b) and not set(b) <= set("-=# ")), "")
        if first and "summary" not in keys:
            keys["summary"] = first
        return keys
    if suffix == ".json":
        try:
            data = json.loads(text)
        except ValueError:
            return {}
        if not isinstance(data, dict):
            return {}
        meta = data.get("_meta")
        if isinstance(meta, dict):
            return {str(k).lower(): str(v) for k, v in meta.items() if str(k).lower() in KEYS}
        note = data.get("_note")
        return {"summary": str(note)} if isinstance(note, str) else {}
    return {}


def tracked(root: pathlib.Path, scopes: list[str]) -> list[pathlib.Path]:
    """Tracked files with a header form under the given folders or files.

    Args:
        root: the project root.
        scopes: project-relative folders or files; empty for the whole project.

    Returns:
        Sorted absolute paths.
    """
    res = subprocess.run(["git", "-C", str(root), "ls-files", "--", *(scopes or ["."])], capture_output=True, text=True, check=False)
    rels = res.stdout.split("\n") if res.returncode == 0 else []
    out = []
    for rel in rels:
        p = root / rel
        if (rel and (p.suffix in HEADER_TYPES or p.name == "justfile") and not any(s in "/" + rel for s in SKIP_PARTS)
                and not p.name.endswith("-baseline.json")):  # machine-written ratchet data
            out.append(p)
    return sorted(out)


def one_line(root: pathlib.Path, path: pathlib.Path, width: int = 150) -> str:
    """The triage line for one file.

    Args:
        root: the project root.
        path: the file.
        width: how much of the summary to show.

    Returns:
        `path  status  review-by-or-last-reviewed  summary`.
    """
    h = read_header(path)
    when = h.get("review by") or h.get("last reviewed", "")
    status = (h.get("status", "") or "-").split(" (")[0][:22]
    summary = " ".join(h.get("summary", h.get("title", "")).split())[:width]
    return f"{str(path.relative_to(root)):<70} {status:<22} {when[:16]:<16} {summary}"


def main(argv: list[str] | None = None) -> int:
    """List headers, or the files missing one.

    Args:
        argv: arguments without the program name; None reads sys.argv.

    Returns:
        The exit code: 0, or 2 when the root is not a directory.
    """
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("scopes", nargs="*")
    ap.add_argument("--project-root", default=".")
    ap.add_argument("--missing", action="store_true", help="list files with no summary instead")
    args = ap.parse_args(argv)
    root = pathlib.Path(args.project_root).resolve()
    if not root.is_dir():
        print(f"not a directory: {root}", file=sys.stderr)
        return 2
    files = tracked(root, args.scopes)
    if args.missing:
        miss = [p for p in files if p.name not in INDEX_NAMES and not read_header(p).get("summary") and not read_header(p).get("title")]
        for p in miss:
            print(p.relative_to(root))
        print(f"{len(miss)} of {len(files)} file(s) have no summary")
        return 0
    for p in files:
        print(one_line(root, p))
    print(f"({len(files)} files; open a file only when its line says you need it)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
