#!/usr/bin/env python3
"""Governance coherence checks for skill-smc.

Turns this pack's governance CLAIMS into assertions that fail. Stdlib only, so the gate never fails for environment reasons; exit 1 on any failure so it can gate a task runner or a manual run.

Generated by skill-ai-it from templates/check_governance.py, tuned to skill-smc's stated rules in AGENTS.md and .archcore/rules/. Doctrine and the inference table live in the skill's
patterns/governance-checks.md — read that before adding, changing, or retiring a check.

Structure:
  CONFIG      — registries tuned to this pack. Everything below CONFIG is generic or skill-smc-specific Tier 3.
  Tier 1      — universal checks (path resolution, catalog coverage).
  Tier 3      — skill-smc-specific invariants; each cites the rule it enforces.

Growth rule: this file is expected to grow with the pack. A new reference file needs no registry change (globs pick it
up automatically) but a new governance surface or restated constant does. When a check fails, fix the pack, not the check.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SELF = Path(__file__).resolve().relative_to(ROOT).as_posix()

# --------------------------------------------------------------------------------------------------------------- CONFIG

# Governance surfaces whose path references must resolve on disk.
SURFACES: tuple[str, ...] = (
    "README.md",
    "AGENTS.md",
    "SKILL.md",
    "RUNBOOK.md",
    "AI_NAVIGATION.md",
)

# Index file -> (folder it indexes, glob). Enforces BOTH directions: every reference file is named in the index, and
# every name in the index resolves to a real file. These four are the surfaces rule-reference-update-discipline.md
# requires to carry a per-file row when a reference is added. The other two surfaces the rule names —
# exports/claude_code/project/skill-smc/adapter.md and install.md — map references/*.md via a wildcard
# (`references/*.md` / `cp references/*.md`), so a per-file catalog check against them would false-fail on every
# reference; they are covered structurally by the wildcard instead and are deliberately not registered here.
CATALOGS: dict[str, tuple[str, str]] = {
    "RUNBOOK.md": ("references", "*.md"),
    "SKILL.md": ("references", "*.md"),
    "AI_NAVIGATION.md": ("references", "*.md"),
    "context-map.yaml": ("references", "*.md"),
    "scripts/README.md": ("scripts", "*"),
}

# Files a catalog may legitimately omit (the index itself, generated output, dotfiles).
CATALOG_EXEMPT: frozenset[str] = frozenset({"README.md", "__init__.py"})

# Lines carrying this marker show an ILLUSTRATIVE filename — a naming-convention example — not a reference to a file
# that must exist.
EXAMPLE_MARKER = "path:example"

# Paths a governance surface references CONDITIONALLY ("when present"), or that are legitimately external-looking
# tokens the path checker should not chase.
CONDITIONAL_PATHS: frozenset[str] = frozenset({
    "graphify-out/GRAPH_REPORT.md",       # generated; this pack has no graphify-out/ yet
    "graphify-out/graph.json",
    "memory-bank/activeContext.md",       # this pack uses SCRATCHPAD.md, not a memory-bank
    "memory-bank/progress.md",
    "memory-bank/decisionLog.md",
    "Taskfile.yml",                       # no Task/Make/Node toolchain here
    "Makefile",
    "package.json",
    "justfile",                           # no root justfile; scripts/ has two scoped ones
    "adapter.md",                         # shorthand in prose for exports/claude_code/project/skill-smc/adapter.md
    "install.md",                         # shorthand in prose for exports/claude_code/project/skill-smc/install.md
    "rule-manifest-version-discipline.md",  # shorthand in prose for .archcore/rules/rule-manifest-version-discipline.md
    "ansible-wifi-root-governance/AGENTS.md",  # lives in the sibling ansible-wifi repo, not this pack
    "issues/apn/routing-issue/AGENTS.md",      # example path from the sibling ansible-wifi repo
    "opa/data",                                # OPA policy layer lives in the sibling ansible-wifi repo
    "opa/policies",
    "references/01_",                     # prose prefix fragment ("references/01_ through references/13_"), not a path
    "references/13_",
    "skill-smc/scripts",                  # shorthand used inside the ansible-wifi cross-repo promotion-checklist text
    "check_note_anchors.py",              # skill-code-context-notes tool script, not part of this pack
    "sbdm.py",                            # Prometheus textfile-collector scripts that run ON the SMC appliance itself
    "smartmon.py",
    "interfacecheckv2.sh",
    "apt_info.py",
    "roles/smc_generate_smc_files",       # Ansible role in the sibling ansible-wifi repo
    "smc_bases.yml",                      # playbook in the sibling ansible-wifi repo
})

# Surfaces scanned for a stray hardcoded pack-version stamp, per rule-manifest-version-discipline.md's explicit list
# ("not RUNBOOK.md, not SKILL.md, not any references/*.md file") plus the other agent-facing governance surfaces.
# CHANGELOG.md and install.md are deliberately excluded — both are append-only history logs where a past version
# number is a historical fact, not a live claim, per the "do not enforce history" doctrine. The check matches only
# THIS pack's current major.minor line (read from manifest.json at run time), not any semver-shaped number — a bare
# `\d+\.\d+\.\d+` pattern collided with unrelated software versions mentioned in the references (ClamAV 0.103.11,
# ansible-lint 0.0.53, etc.), which are not this pack's version stamp at all.
VERSION_STAMP_SURFACES: tuple[str, ...] = ("RUNBOOK.md", "SKILL.md", "AGENTS.md", "README.md", "AI_NAVIGATION.md")

# Path-token discrimination (Tier 1 path check).
PATHLIKE = re.compile(r"^[A-Za-z0-9._/-]+$")
REPO_SUFFIXES: frozenset[str] = frozenset({".md", ".py", ".json", ".yaml", ".yml", ".toml", ".sh", ".txt"})
IGNORE_PREFIXES: tuple[str, ...] = ("http://", "https://", "mailto:", "~/", "/")
IGNORE_EXACT: frozenset[str] = frozenset({"README.md", "AGENTS.md", "CLAUDE.md", "SCRATCHPAD.md", "CHANGELOG.md"})

# --------------------------------------------------------------------------------------------------------------- HARNESS

failures: list[str] = []
checks_run = 0


def fail(check: str, detail: str) -> None:
    failures.append(f"{check}: {detail}")


def counted() -> None:
    global checks_run
    checks_run += 1


def read(rel: str) -> str | None:
    path = ROOT / rel
    return path.read_text(encoding="utf-8") if path.is_file() else None


def without_code(text: str) -> str:
    return re.sub(r"```.*?```", "", text, flags=re.DOTALL)


def members(folder: str, glob: str) -> list[Path]:
    base = ROOT / folder
    if not base.is_dir():
        return []
    return sorted(p for p in base.glob(glob) if p.is_file() and not p.name.startswith("."))


# --------------------------------------------------------------------------------------------------------------- TIER 1


def check_referenced_paths() -> None:
    """Every repo-relative path named in a governance surface resolves on disk."""
    for surface in SURFACES:
        text = read(surface)
        if text is None:
            fail("surface", f"{surface} is listed as a governance surface but does not exist")
            counted()
            continue
        body = "\n".join(l for l in without_code(text).splitlines() if EXAMPLE_MARKER not in l)
        tokens = set(re.findall(r"`([^`\n]+)`", body))
        tokens |= {m.group(1) for m in re.finditer(r"\]\(([^)\s]+)\)", body)}
        for raw in sorted(tokens):
            tok = raw.split("#", 1)[0].strip().rstrip("/")
            if not tok or tok in IGNORE_EXACT or tok in CONDITIONAL_PATHS or tok.startswith(IGNORE_PREFIXES):
                continue
            if not PATHLIKE.match(tok):
                continue
            suffix = Path(tok).suffix
            if "/" not in tok and suffix not in REPO_SUFFIXES:
                continue
            if suffix and suffix not in REPO_SUFFIXES:
                continue
            counted()
            near = (ROOT / surface).parent / tok
            if not near.exists() and not (ROOT / tok).exists():
                fail("path", f"{surface} references `{tok}` which does not exist")


def check_catalog_coverage() -> None:
    """Both directions: the catalog names nothing missing, and nothing present is uncataloged.

    Enforces rule-reference-update-discipline.md's per-file surfaces (RUNBOOK.md, SKILL.md, AI_NAVIGATION.md,
    context-map.yaml) and the pack's own scripts/README.md inventory convention.
    """
    for index, (folder, glob) in CATALOGS.items():
        text = read(index)
        if text is None:
            fail("catalog", f"{index} is registered as a catalog but does not exist")
            counted()
            continue
        body = without_code(text)
        for item in members(folder, glob):
            if item.name in CATALOG_EXEMPT or (ROOT / index).resolve() == item.resolve():
                continue
            counted()
            if item.name not in body:
                fail("coverage", f"{folder}/{item.name} exists but is not cataloged in {index}")


# --------------------------------------------------------------------------------------------------------------- TIER 3
# Pack-specific invariants. Each check states, in its docstring, the rule it enforces and where that rule lives.


def check_version_single_source() -> None:
    """manifest.json is the sole version-of-record; no other governance surface may hardcode a duplicate.

    Rule: .archcore/rules/rule-manifest-version-discipline.md. A second hardcoded copy drifts because no other rule
    updates it on a bump — this happened twice already (RUNBOOK.md header carried a stale 0.1.28 against manifest's
    0.1.29; SKILL.md's Source footer carried the same risk), both fixed 2026-09-08. CHANGELOG.md and install.md are
    deliberately excluded: both are append-only history logs where a past version number is a historical fact, not
    a live claim.
    """
    manifest = read("manifest.json")
    if manifest is None:
        fail("version-single-source", "manifest.json does not exist — it is the sole version-of-record")
        counted()
        return
    try:
        current = str(json.loads(manifest).get("version", ""))
    except json.JSONDecodeError:
        fail("version-single-source", "manifest.json does not parse as JSON")
        counted()
        return
    parts = current.split(".")
    if len(parts) < 2:
        fail("version-single-source", f"manifest.json version {current!r} is not in major.minor.patch form")
        counted()
        return
    prefix = f"{parts[0]}.{parts[1]}"
    pattern = re.compile(rf"\bv?{re.escape(prefix)}\.\d+\b")

    surfaces = list(VERSION_STAMP_SURFACES) + [
        p.relative_to(ROOT).as_posix() for p in members("references", "*.md")
    ]
    for surface in surfaces:
        text = read(surface)
        if text is None:
            continue
        counted()
        for m in pattern.finditer(without_code(text)):
            fail(
                "version-single-source",
                f"{surface} hardcodes version stamp {m.group(0)!r} — manifest.json is the sole "
                f"version-of-record; point to it instead of restating the number",
            )


# --------------------------------------------------------------------------------------------------------------- MAIN

CHECKS = (
    check_referenced_paths,
    check_catalog_coverage,
    check_version_single_source,
)


def main() -> int:
    for check in CHECKS:
        check()

    unique = sorted(set(failures))
    if unique:
        print(f"FAIL — {len(unique)} issue(s) across {checks_run} checks\n")
        for f in unique:
            print(f"  ✗ {f}")
        return 1

    print(f"OK — {checks_run} governance checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
