#!/usr/bin/env python3
"""Governance coherence checks for skill-smc.

Turns this pack's governance CLAIMS into assertions that fail. Stdlib only, so the gate never fails for environment reasons; exit 1 on any failure so it can gate a task runner or a manual run.

Generated by skill-ai-it from templates/check_governance.py, tuned to skill-smc's stated rules in AGENTS.md and .archcore/rules/. Doctrine and the inference table live in the skill's
patterns/governance-checks.md — read that before adding, changing, or retiring a check.

Structure:
  CONFIG      — registries tuned to this pack. Everything below CONFIG is generic or skill-smc-specific Tier 3.
  Tier 1      — universal checks (path resolution, catalog coverage).
  Tier 3      — skill-smc-specific invariants; each cites the rule it enforces.

Growth rule: this file is expected to grow with the pack. A new reference file needs no registry change (globs pick it
up automatically) but a new governance surface or restated constant does. When a check fails, fix the pack, not the check.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SELF = Path(__file__).resolve().relative_to(ROOT).as_posix()

# --------------------------------------------------------------------------------------------------------------- CONFIG

# Governance surfaces whose path references must resolve on disk.
# DERIVED, not hand-listed. Until 2026-09-20 this was a fixed tuple, so `references/**` — where this package's
# actual content lives — sat outside every path check. The sibling project `unified-network-controller` had the same
# hole and it hid two genuinely broken links under a green suite; see its
# `.archcore/rules/govern-a-derived-population-never-a-hand-list.rule.md`. A check's POPULATION is derived; a check's
# PERMISSIONS (CONDITIONAL_PATHS, markers) stay explicit and per-entry reasoned.
#
# `references/**` is EXCLUDED, and the reason is stated rather than left as an omission: those files use slash
# notation for things that are not filesystem paths — device paths, CIDR blocks, systemd unit paths, sibling-repo
# paths — and a path check run over them reports mostly non-defects, which is a check nobody reads. Bringing them in
# needs a token discriminator, not a longer exemption list. Their split-path tokens ARE checked, by
# check_split_path_tokens, which scans every markdown file in the package.
# A path claim may legitimately name a file in a SIBLING repo — this package's entire subject is the `ansible-wifi`
# repository, and its prose names roles, inventories and flavour files by their path THERE. Declaring those roots
# makes such references VERIFIED rather than merely unchecked: if ansible-wifi renames a role, this package's routing
# into it fails loudly instead of quietly pointing nowhere. An absent root is reported as SKIPPED, never as passed.
SIBLING_ROOTS: dict[str, str] = {
    "self-parent":   "..",
    "ansible-wifi":  "../../../../../../_ansible/ansible-wifi",
    "ansible-notes": "../../../../../../_ansible/local-knowledge-ansible/ansible-wifi",
    "ansible-root":  "../../../../../../_ansible",
    "apn-projects":  "../../../../../_project/project_stuff/apn",
    "skill-cambium": "../skill-cambium",
}


def _sibling_roots() -> list[Path]:
    roots: list[Path] = []
    for name, rel in sorted(SIBLING_ROOTS.items()):
        base = (ROOT / rel).resolve()
        if base.is_dir():
            roots.append(base)
        else:
            print(f"  ... SKIPPED (not passed): sibling root `{name}` absent at {rel}; its references were not verified")
    return roots


_APPEND_ONLY: frozenset[str] = frozenset({"CHANGELOG.md", "SCRATCHPAD.md"})


def _live_surfaces() -> tuple[str, ...]:
    found = [p.relative_to(ROOT).as_posix()
             for pat in ("*.md", "scripts/README.md")
             for p in ROOT.glob(pat)]
    # These two are append-only history. Its entries name files by the basename they carried when the entry was
    # written, which is a true record of what was true then — "exempt history by marker, never by rewriting it".
    # Rewriting past entries to satisfy a path check is the failure that exemption exists to prevent. SCRATCHPAD.md's
    # session log is the same shape: its 2026-06-26 entry records that a dead `references/PROFILE.md` pointer was
    # REMOVED, which a path check reads as a live broken reference. The gain from deriving the population is the
    # files that were never in scope at all — ARCHITECTURE.md, PROFILE.md, SYSTEM_PROMPT.md, and anything added
    # later — not these two.
    return tuple(sorted(s for s in set(found) if s not in _APPEND_ONLY))



# Index file -> (folder it indexes, glob). Enforces BOTH directions: every reference file is named in the index, and
# every name in the index resolves to a real file. These four are the surfaces rule-reference-update-discipline.md
# requires to carry a per-file row when a reference is added. The other two surfaces the rule names —
# exports/claude_code/project/skill-smc/adapter.md and install.md — map references/*.md via a wildcard
# (`references/*.md` / `cp references/*.md`), so a per-file catalog check against them would false-fail on every
# reference; they are covered structurally by the wildcard instead and are deliberately not registered here.
CATALOGS: dict[str, tuple[str, str]] = {
    "RUNBOOK.md": ("references", "*.md"),
    "SKILL.md": ("references", "*.md"),
    "AI_NAVIGATION.md": ("references", "*.md"),
    "context-map.yaml": ("references", "*.md"),
    "scripts/README.md": ("scripts", "*"),
}

# Files a catalog may legitimately omit (the index itself, generated output, dotfiles).
CATALOG_EXEMPT: frozenset[str] = frozenset({"README.md", "__init__.py"})

# Lines carrying this marker show an ILLUSTRATIVE filename — a naming-convention example — not a reference to a file
# that must exist.
EXAMPLE_MARKER = "path:example"

# Paths a governance surface references CONDITIONALLY ("when present"), or that are legitimately external-looking
# tokens the path checker should not chase.
CONDITIONAL_PATHS: frozenset[str] = frozenset({
    # Names the evidence collector PRODUCES, documented so an operator knows what to expect in a capture bundle.
    # They are outputs, not inputs, and nothing in this package is required to contain them.
    "01-identity-hardware.txt",
    "02-services-security.txt",
    "03-apps-scripts-cron.txt",
    "04-portal-packages.txt",
    "05-portal-fqdn-status.txt",
    "MANIFEST.txt",
    "SUMMARY.txt",                        # also ambiguous: four captures carry this name, by design
    # Not filesystem paths at all, despite the slash.
    "origin/main",                        # git ref
    "origin/master",                      # git ref
    "wifi/access",                        # Apache log name on the SMC appliance, not a path in this repo
    "scripts/scripts/...",                # ellipsis in prose showing a nesting shape, not a real path
    # Fragments of this package's own canonical absolute path, quoted in prose about where it lives.
    "specialists/project",
    "skills_stuff/specialists/project/skill-smc",
    "graphify-out/GRAPH_REPORT.md",       # generated; this pack has no graphify-out/ yet
    "graphify-out/graph.json",
    "memory-bank/activeContext.md",       # this pack uses SCRATCHPAD.md, not a memory-bank
    "memory-bank/progress.md",
    "memory-bank/decisionLog.md",
    "Taskfile.yml",                       # no Task/Make/Node toolchain here
    "Makefile",
    "package.json",
    "justfile",                           # no root justfile; scripts/ has two scoped ones
    "adapter.md",                         # shorthand in prose for exports/claude_code/project/skill-smc/adapter.md
    "install.md",                         # shorthand in prose for exports/claude_code/project/skill-smc/install.md
    "rule-manifest-version-discipline.md",  # shorthand in prose for .archcore/rules/rule-manifest-version-discipline.md
    "ansible-wifi-root-governance/AGENTS.md",  # lives in the sibling ansible-wifi repo, not this pack
    "issues/apn/routing-issue/AGENTS.md",      # example path from the sibling ansible-wifi repo
    "opa/data",                                # OPA policy layer lives in the sibling ansible-wifi repo
    "opa/policies",
    "references/01_",                     # prose prefix fragment ("references/01_ through references/13_"), not a path
    "references/13_",
    "skill-smc/scripts",                  # shorthand used inside the ansible-wifi cross-repo promotion-checklist text
    "check_note_anchors.py",              # skill-code-context-notes tool script, not part of this pack
    "sbdm.py",                            # Prometheus textfile-collector scripts that run ON the SMC appliance itself
    "smartmon.py",
    "interfacecheckv2.sh",
    "apt_info.py",
    "roles/smc_generate_smc_files",       # Ansible role in the sibling ansible-wifi repo
    "smc_bases.yml",                      # playbook in the sibling ansible-wifi repo
})

# Surfaces scanned for a stray hardcoded pack-version stamp, per rule-manifest-version-discipline.md's explicit list
# ("not RUNBOOK.md, not SKILL.md, not any references/*.md file") plus the other agent-facing governance surfaces.
# CHANGELOG.md and install.md are deliberately excluded — both are append-only history logs where a past version
# number is a historical fact, not a live claim, per the "do not enforce history" doctrine. The check matches only
# THIS pack's current major.minor line (read from manifest.json at run time), not any semver-shaped number — a bare
# `\d+\.\d+\.\d+` pattern collided with unrelated software versions mentioned in the references (ClamAV 0.103.11,
# ansible-lint 0.0.53, etc.), which are not this pack's version stamp at all.
VERSION_STAMP_SURFACES: tuple[str, ...] = ("RUNBOOK.md", "SKILL.md", "AGENTS.md", "README.md", "AI_NAVIGATION.md")

# Path-token discrimination (Tier 1 path check).
PATHLIKE = re.compile(r"^[A-Za-z0-9._/-]+$")
REPO_SUFFIXES: frozenset[str] = frozenset({".md", ".py", ".json", ".yaml", ".yml", ".toml", ".sh", ".txt"})
IGNORE_PREFIXES: tuple[str, ...] = ("http://", "https://", "mailto:", "~/", "/")
IGNORE_EXACT: frozenset[str] = frozenset({"README.md", "AGENTS.md", "CLAUDE.md", "SCRATCHPAD.md", "CHANGELOG.md"})

# --------------------------------------------------------------------------------------------------------------- HARNESS

failures: list[str] = []
checks_run = 0


def fail(check: str, detail: str) -> None:
    failures.append(f"{check}: {detail}")


def counted() -> None:
    global checks_run
    checks_run += 1


def read(rel: str) -> str | None:
    path = ROOT / rel
    return path.read_text(encoding="utf-8") if path.is_file() else None


def without_code(text: str) -> str:
    return re.sub(r"```.*?```", "", text, flags=re.DOTALL)


def members(folder: str, glob: str) -> list[Path]:
    base = ROOT / folder
    if not base.is_dir():
        return []
    return sorted(p for p in base.glob(glob) if p.is_file() and not p.name.startswith("."))


# --------------------------------------------------------------------------------------------------------------- TIER 1


def check_split_path_tokens() -> None:
    """No backticked path is split across two table rows by a trailing backslash.

    A wide table cell wraps mid-filename and leaves the token ending in a backslash with its tail on the next row.
    The reference is unfollowable for a reader and invisible to check_referenced_paths, which skips anything that
    does not look like a path — so the defect hides from the very check that should catch it. Found 20 times across
    this package and its siblings on 2026-09-20. A line that legitimately discusses backslash continuation carries
    the EXAMPLE_MARKER.
    """
    for path in sorted(ROOT.rglob("*.md")):
        rel = path.relative_to(ROOT).as_posix()
        if rel.startswith((".git/", "graphify-out/", ".ai-context/")) or rel == "CHANGELOG.md":
            continue
        counted()  # one assertion per FILE: "this file splits no path token across rows".
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if EXAMPLE_MARKER in line:
                continue
            for m in re.finditer(r"`([^`\n]*\\)`", line):
                fail("split-path", f"{rel}:{number} splits `{m.group(1)}` across rows; a wrapped table cell broke a "
                                   f"path token in half — join it onto one line")


def check_referenced_paths() -> None:
    """Every repo-relative path named in a governance surface resolves on disk."""
    _siblings = _sibling_roots()
    for surface in _live_surfaces():
        text = read(surface)
        if text is None:
            fail("surface", f"{surface} is listed as a governance surface but does not exist")
            counted()
            continue
        body = "\n".join(l for l in without_code(text).splitlines() if EXAMPLE_MARKER not in l)
        tokens = set(re.findall(r"`([^`\n]+)`", body))
        tokens |= {m.group(1) for m in re.finditer(r"\]\(([^)\s]+)\)", body)}
        for raw in sorted(tokens):
            tok = raw.split("#", 1)[0].strip().rstrip("/")
            if not tok or tok in IGNORE_EXACT or tok in CONDITIONAL_PATHS or tok.startswith(IGNORE_PREFIXES):
                continue
            if not PATHLIKE.match(tok):
                continue
            suffix = Path(tok).suffix
            if "/" not in tok and suffix not in REPO_SUFFIXES:
                continue
            if suffix and suffix not in REPO_SUFFIXES:
                continue
            counted()
            if ((ROOT / surface).parent / tok).exists() or (ROOT / tok).exists():
                continue
            if any((b / tok).exists() for b in _siblings):
                continue
            # A BARE basename — `01_overview.md`, `flavors.json` — is how this package's own prose refers to its
            # reference and config files, and that is legitimate: within one package the name is unambiguous. It
            # resolves only on a UNIQUE match, so a rename still fails and an ambiguous name is reported rather
            # than silently accepted.
            if "/" not in tok:
                hits = [h for h in ROOT.rglob(tok)
                        if not h.relative_to(ROOT).as_posix().startswith((".git/", ".ai-context/", "graphify-out/"))]
                if len(hits) == 1:
                    continue
                if len(hits) > 1:
                    fail("path", f"{surface} references `{tok}`, which is ambiguous — {len(hits)} files carry that "
                                 f"name; qualify it with its folder")
                    continue
            fail("path", f"{surface} references `{tok}` which does not exist")


def check_catalog_coverage() -> None:
    """Both directions: the catalog names nothing missing, and nothing present is uncataloged.

    Enforces rule-reference-update-discipline.md's per-file surfaces (RUNBOOK.md, SKILL.md, AI_NAVIGATION.md,
    context-map.yaml) and the pack's own scripts/README.md inventory convention.
    """
    for index, (folder, glob) in CATALOGS.items():
        text = read(index)
        if text is None:
            fail("catalog", f"{index} is registered as a catalog but does not exist")
            counted()
            continue
        body = without_code(text)
        for item in members(folder, glob):
            if item.name in CATALOG_EXEMPT or (ROOT / index).resolve() == item.resolve():
                continue
            counted()
            if item.name not in body:
                fail("coverage", f"{folder}/{item.name} exists but is not cataloged in {index}")


# --------------------------------------------------------------------------------------------------------------- TIER 3
# Pack-specific invariants. Each check states, in its docstring, the rule it enforces and where that rule lives.


def check_version_single_source() -> None:
    """manifest.json is the sole version-of-record; no other governance surface may hardcode a duplicate.

    Rule: .archcore/rules/rule-manifest-version-discipline.md. A second hardcoded copy drifts because no other rule
    updates it on a bump — this happened twice already (RUNBOOK.md header carried a stale 0.1.28 against manifest's
    0.1.29; SKILL.md's Source footer carried the same risk), both fixed 2026-09-08. CHANGELOG.md and install.md are
    deliberately excluded: both are append-only history logs where a past version number is a historical fact, not
    a live claim.
    """
    manifest = read("manifest.json")
    if manifest is None:
        fail("version-single-source", "manifest.json does not exist — it is the sole version-of-record")
        counted()
        return
    try:
        current = str(json.loads(manifest).get("version", ""))
    except json.JSONDecodeError:
        fail("version-single-source", "manifest.json does not parse as JSON")
        counted()
        return
    parts = current.split(".")
    if len(parts) < 2:
        fail("version-single-source", f"manifest.json version {current!r} is not in major.minor.patch form")
        counted()
        return
    prefix = f"{parts[0]}.{parts[1]}"
    pattern = re.compile(rf"\bv?{re.escape(prefix)}\.\d+\b")

    surfaces = list(VERSION_STAMP_SURFACES) + [
        p.relative_to(ROOT).as_posix() for p in members("references", "*.md")
    ]
    for surface in surfaces:
        text = read(surface)
        if text is None:
            continue
        counted()
        for m in pattern.finditer(without_code(text)):
            fail(
                "version-single-source",
                f"{surface} hardcodes version stamp {m.group(0)!r} — manifest.json is the sole "
                f"version-of-record; point to it instead of restating the number",
            )


# --------------------------------------------------------------------------------------------------------------- MAIN

CHECKS = (
    check_referenced_paths,
    check_split_path_tokens,
    check_catalog_coverage,
    check_version_single_source,
)


def main() -> int:
    for check in CHECKS:
        check()

    unique = sorted(set(failures))
    if unique:
        print(f"FAIL — {len(unique)} issue(s) across {checks_run} checks\n")
        for f in unique:
            print(f"  ✗ {f}")
        return 1

    print(f"OK — {checks_run} governance checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
