#!/usr/bin/env python3
"""Governance coherence checks for Agent Stack.

Turns this project's governance CLAIMS into assertions that fail. Stdlib only, so the gate never fails for environment reasons; exit 1 on any failure so it can
gate the task runner.

Generated by skill-ai-it from templates/check_governance.py. Doctrine, check families, and the inference table live in the skill's patterns/governance-checks.md
— read that before adding, changing, or retiring a check.

Structure:
  CONFIG      — registries the agent tunes per project. Everything below CONFIG is generic.
  Tier 1      — universal checks. Present in every project.
  Tier 2      — conditional checks. Kept only when their trigger artifact exists.
  Tier 3      — project-specific invariants. Authored per project; each cites the rule it enforces.

Growth rule: this file is expected to grow with the project. A new class of artifact needs a coverage check; a new duplicated constant needs a registry entry.
When a check fails, fix the project, not the check.

Checks:
  1. Referenced paths in the governance surfaces resolve on disk (relative to the referencing file, then to the repo root).
  2. Index links resolve, and every indexed folder member is linked.
  3. Count claims in prose match reality (historical facts exempt).
  4. Cataloged items exist and existing items are cataloged.
  5. Task-runner recipes named in prose exist in the runner.
  6. Derived artifacts are not older than their inputs.
  7. Every surface restating a registered constant states it identically, and nothing unregistered restates it.
  8. Every row of an append-only table stamps its pass, and no pass records the same entity twice.
  9. Every dated evidence capture states its URL, retrieval date and HTTP status, or names the capture that corrects it.
"""

from __future__ import annotations

import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Repo-relative path to this file. Used to exclude the checker from the constant scan: it necessarily contains every registered constant's PATTERN, and
# comparing `rel` against a bare `Path(__file__).name` never matched, so the checker reported each of its own pattern definitions as an unregistered
# restatement.
SELF = Path(__file__).resolve().relative_to(ROOT).as_posix()

# --------------------------------------------------------------------------------------------------------------- CONFIG
# Tune these registries to the project. Leave a registry empty and its check contributes zero assertions rather than failing — coverage is measured by the
# assertion count, so an empty registry reads honestly as "not covered yet".

# Governance surfaces whose path references must resolve.
SURFACES: tuple[str, ...] = (
    "README.md",
    "AGENTS.md",
    "SCRATCHPAD.md",
    "CHANGELOG.md",
    "MEMORY.md",
    "AI_NAVIGATION.md",
    "RUNTIME.md",
    "SKILL_STANDARD.md",
    "REVISION_NOTES.md",
    "ROUTING_EVALS.md",
    "ARCHITECTURE.md",
)

# Index file -> (folder it indexes, glob). Enforces BOTH directions: links resolve, and members are linked.
CATALOGS: dict[str, tuple[str, str]] = {
    "scripts/README.md": ("scripts", "*.py"),
    # The durable-truth index. `**/*.md` is deliberate: .archcore/ documents live in adr/rules/specs/guides/plans subfolders, and a non-recursive glob would
    # report full coverage while checking nothing. Points at the INDEX rather than at the candidate queue, which /skill-ai-it promote deletes by contract.
    ".archcore/README.md": (".archcore", "**/*.md"),
    # Working documents — audits, proposals, classifications, evaluation records. Registered when the root was cleared of them on 2026-09-02: the root now
    # carries governance and contract entrypoints only, and an unindexed document in docs/ would otherwise be invisible to every reader and every check.
    # `**/*.md` since 2026-09-04: docs/ grew subfolders (audits/, routing-evaluation/, reliability-adaptation/, off-topic/) once the flat list passed a dozen
    # files, and a non-recursive glob would report full coverage while checking nothing inside them — the same reasoning already applied to .archcore/ above.
    "docs/README.md": ("docs", "**/*.md"),
    # The persona library. Registered 20260903 after the inverse sweep found personas/ was the one library layer with no index at all — 15 documents and no way
    # in, while skills/ and .archcore/ both had one. Coverage now fails until a new persona is linked here, which is the intended workflow rather than an error.
    "personas/README.md": ("personas", "*.md"),
}

# Files a catalog may legitimately omit (the index itself, generated output, dotfiles).
CATALOG_EXEMPT: frozenset[str] = frozenset({"README.md", "__init__.py"})

# Countable noun -> (folder, glob). A prose claim like "26 documents" is checked against the real count. Choose the glob deliberately: "*.md" counts the
# folder's own index too, which is usually not what the prose means — prefer "[0-9]*.md" or a similar shape when the index is excluded from the claim.
# "personas" is countable as files; skill PACKAGES are directories, so members() cannot see them — that count is asserted against the manifest in
# check_library_counts() instead.
COUNT_CLAIMS: dict[str, tuple[str, str]] = {
    # "[a-z]*-*.md" excludes README.md: the index is not a persona, and counting it made every "15 personas" claim in the project read as wrong
    # the moment the index was created. The registry comment above says to choose this glob deliberately; this is that case.
    "personas": ("personas", "[a-z]*-*.md"),
}

# Lines carrying this marker state a historical fact, not a live claim, and are exempt from count checking.
ASAT_MARKER = "count:asat"

# Lines carrying this marker show an ILLUSTRATIVE filename — a naming-convention example — not a reference to a file that must exist. Same shape as ASAT_MARKER:
# explicit, per line, and visible in the document itself rather than hidden in an ignore-list here.
EXAMPLE_MARKER = "path:example"

# Paths a governance surface references CONDITIONALLY ("when present"). The generic skill-ai-it navigation block names several; each is a real artifact in SOME
# governed project, so its absence here is a fact about this project's toolchain rather than a broken reference. Registered with a per-entry reason rather than
# silently ignore-listed, so the exemption stays reviewable — remove an entry the day the artifact appears. Tune per project.
CONDITIONAL_PATHS: frozenset[str] = frozenset({
    "Taskfile.yml",                    # this project uses just, not Task
    "Makefile",                        # no make-based entrypoint
    "package.json",                    # no Node toolchain in the maintenance runtime
    "graphify-out/GRAPH_REPORT.md",    # generated; absent until the graph task has run
    "graphify-out/graph.json",
    ".ai-context/governance-pack.md",  # generated; absent until `just context-pack` has run
    ".ai-context/repo-pack.md",
    "memory-bank/activeContext.md",    # this project uses SCRATCHPAD.md, not a memory-bank
    "memory-bank/progress.md",
    "memory-bank/decisionLog.md",
    "translation-brief.md",            # emitted by a sync run into the working cache, not committed here
    # RETIRED 20260903 when upstream sync was removed. Registered rather than unbackticked because a changelog recording a removal must be able to NAME what it
    # removed, and the .archcore records superseded in place still describe how these worked. Same reasoning that put ARCHCORE_PROMOTION_CANDIDATES.md here.
    "scripts/sync_auto_company.py",
    "upstream-state.json",
    "translation-memory.json",
    "translation-policy.md",
    "tests/test_sync_auto_company.py",
    # Paths that are real, and deliberately NOT inside this repo. Registered with a reason rather than ignore-listed so the exemption stays reviewable.
    ".agents/skills",                              # consumer-side discovery path created by install_global.py
    "skills-working-cache/agent-stack/update-reports",  # sync reports land in the working-cache peer, never in source
    "MaxMiksa/Auto-Company",                       # upstream GitHub repo slug, not a path in this tree
    # Transient by design: it is a proposal queue that `/skill-ai-it promote` deletes once its candidates become .archcore/ documents. Registered so
    # CHANGELOG.md's historical mention of it does not fail path resolution after the file is gone — history is not a live claim. The durable index after
    # promotion is .archcore/README.md.
    "ARCHCORE_PROMOTION_CANDIDATES.md",
})

# Task runner file, or None if the project has none.
TASK_RUNNER: str | None = "justfile"

# Files whose prose names task-runner recipes.
RUNNER_REFERENCES: tuple[str, ...] = (
    "README.md",
    "AGENTS.md",
    "AI_NAVIGATION.md",
    "RUNTIME.md",
    "SKILL_STANDARD.md",
    "scripts/README.md",
)

# Generated artifact -> inputs it must not be older than.
DERIVED: dict[str, tuple[str, ...]] = {
    # "docs/CLASS-PROFILES.md": ("scripts/class_profiles.py", "process/vehicle-classes.yaml"),
}

# Facts deliberately restated across surfaces. Each entry: the regex that recognises a statement of the fact, and every file allowed to state it. Drift fails;
# so does an UNREGISTERED file stating it — that is what makes this self-extending. Pair each entry with a spec document explaining why the duplication is
# intentional.
CONSTANT_SURFACES: dict[str, dict[str, object]] = {
    # "profit-gate": { "pattern": r"\$2,500", "surfaces": ("AGENTS.md", "docs/07-DECISIONS.md"), "owner": ".archcore/rules/purchase-discipline.rule.md", },
}

# Append-only tables and the columns that give them their grain: (entity column, pass column). An append-only table records a re-measurement by ADDING a row,
# which is right and useless on its own — without a column that orders the passes there is no way to compute which row is current, and every aggregate over the
# table double-counts whatever was re-measured. Found in a governed project on 2026-08-28 with twelve rows standing for eight entities, the supersession
# recorded only in a prose note. Register the table here and the grain becomes an assertion instead of an intention.
APPEND_ONLY_TABLES: dict[str, tuple[str, str]] = {
    # "data/sku-scores.csv": ("sku_id", "scored_at"),
}

# YAML surfaces whose key stream is checked for duplicates. A duplicate key parses fine and silently discards a block, so well-formedness cannot catch it.
YAML_SURFACES: tuple[str, ...] = ("context-map.yaml", "manifest.yaml")

# Tracked JSONL evidence: append-only files written by one script and read by another. A malformed or under-populated line does not raise anywhere — the writer
# has already exited and the reader skips what it cannot parse — so evidence goes missing with no error. Maps each file to the keys every line must carry.
JSONL_EVIDENCE: dict[str, tuple[str, ...]] = {
    "evals/field-log.jsonl": ("ts", "task", "project", "owner", "followed"),
    "evals/capability-gaps.jsonl": ("at", "kind", "persona", "text"),
}

# Folder of dated evidence captures, or None if the project keeps none. A capture asserts what a source said on a date.
EVIDENCE_DIR: str | None = None  # e.g. "trackers/source-captures"

# The index file inside EVIDENCE_DIR, exempt from the provenance header because it is a catalog, not a capture.
EVIDENCE_INDEX = "README.md"

# Header fields that make a capture re-openable by someone who was not there: where it came from, when, and whether the fetch actually succeeded. A capture
# naming no URL and no HTTP status is a recollection in a capture's clothing — in the project this was promoted from, exactly that produced a VERIFIED cost row
# whose only recorded fetch returned 403.
EVIDENCE_PROVENANCE_FIELDS: tuple[str, ...] = ("Canonical URL", "Retrieved", "HTTP status")

# Captures taken before the provenance rule existed. Each MUST name the later capture supplying the missing provenance — this is a correction record, not an
# exemption. Where captures are immutable the only way to clear an entry is to take the correcting capture, which is the behaviour the rule wants. Removing an
# entry whose correction does not exist turns the check red rather than quiet, so the list cannot be emptied by deletion.
EVIDENCE_PROVENANCE_CORRECTED: dict[str, str] = {
    # "uae-wholesale-moq-discounts-20260828.md": "wholesale-house-price-provenance-20260828.md",
}

# Extensions scanned when hunting for unregistered restatements of a constant.
SCAN_SUFFIXES: frozenset[str] = frozenset({".md", ".py", ".yaml", ".yml"})

# Path-token discrimination. Prose is full of tokens that look like paths and are not; tune until the check is quiet.
PATHLIKE = re.compile(r"^[A-Za-z0-9._/-]+$")
REPO_SUFFIXES: frozenset[str] = frozenset({".md", ".py", ".json", ".yaml", ".yml", ".toml", ".sh", ".txt"})
IGNORE_PREFIXES: tuple[str, ...] = ("http://", "https://", "mailto:", "~/", "/")
# "SKILL.md" joins the generic filenames: SKILL_STANDARD.md discusses the shape every skill's SKILL.md must have, which is a convention, not a reference to one
# file at the repo root.
IGNORE_EXACT: frozenset[str] = frozenset(
    {"README.md", "AGENTS.md", "CLAUDE.md", "SCRATCHPAD.md", "CHANGELOG.md", "SKILL.md"}
)

# --------------------------------------------------------------------------------------------------------------- HARNESS

failures: list[str] = []
checks_run = 0


def fail(check: str, detail: str) -> None:
    failures.append(f"{check}: {detail}")


def counted() -> None:
    """Record one assertion actually evaluated. Never call this per function — only per real comparison."""
    global checks_run
    checks_run += 1


def read(rel: str) -> str | None:
    path = ROOT / rel
    return path.read_text(encoding="utf-8") if path.is_file() else None


def without_code(text: str) -> str:
    """Strip fenced code blocks. Their contents are examples, not claims about this repo."""
    return re.sub(r"```.*?```", "", text, flags=re.DOTALL)


def table_rows(rel: str) -> list[dict[str, str]]:
    """Read a CSV as dicts, or an empty list when it does not exist — an absent table contributes zero assertions."""
    path = ROOT / rel
    if not path.is_file():
        return []
    with path.open(encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def members(folder: str, glob: str) -> list[Path]:
    base = ROOT / folder
    if not base.is_dir():
        return []
    return sorted(p for p in base.glob(glob) if p.is_file() and not p.name.startswith("."))


# --------------------------------------------------------------------------------------------------------------- TIER 1


def check_referenced_paths() -> None:
    """Every repo-relative path named in a governance surface resolves on disk."""
    for surface in SURFACES:
        text = read(surface)
        if text is None:
            fail("surface", f"{surface} is listed as a governance surface but does not exist")
            counted()
            continue
        body = "\n".join(l for l in without_code(text).splitlines() if EXAMPLE_MARKER not in l)
        tokens = set(re.findall(r"`([^`\n]+)`", body))
        tokens |= {m.group(1) for m in re.finditer(r"\]\(([^)\s]+)\)", body)}
        for raw in sorted(tokens):
            tok = raw.split("#", 1)[0].strip().rstrip("/")
            if not tok or tok in IGNORE_EXACT or tok in CONDITIONAL_PATHS or tok.startswith(IGNORE_PREFIXES):
                continue
            if not PATHLIKE.match(tok):
                continue
            # A token with no letters is not a path. `2/3`, `16/19`, `60/60` are fractions and scores, and this project's prose is full of them; three false
            # failures in one session (`n/a`, `2/3`, and a near-miss on a ratio) is enough evidence that the exclusion is needed. It cannot hide a real path,
            # because every path in this repo contains at least one letter — asserted below so the exemption cannot silently widen.
            if not any(c.isalpha() for c in tok):
                continue
            suffix = Path(tok).suffix
            if "/" not in tok and suffix not in REPO_SUFFIXES:
                continue
            if suffix and suffix not in REPO_SUFFIXES:
                continue
            counted()
            # Resolve relative to the file that MAKES the reference first, then relative to ROOT. Resolving only against ROOT false-fails every correct relative
            # link written inside a subfolder README.
            near = (ROOT / surface).parent / tok
            if not near.exists() and not (ROOT / tok).exists():
                fail("path", f"{surface} references `{tok}` which does not exist")


def check_index_links() -> None:
    """Links inside an index file resolve, relative to the index's own folder."""
    for index in CATALOGS:
        text = read(index)
        if text is None:
            fail("index", f"catalog {index} does not exist")
            counted()
            continue
        base = (ROOT / index).parent
        for target in {m.group(1) for m in re.finditer(r"\]\(([^)\s]+)\)", without_code(text))}:
            tok = target.split("#", 1)[0].strip()
            if not tok or tok.startswith(IGNORE_PREFIXES):
                continue
            counted()
            if not (base / tok).exists():
                fail("index", f"{index} links `{tok}` which does not exist")


def check_count_claims() -> None:
    """Prose stating a quantity matches the real count. Lines marked as historical facts are exempt."""
    for noun, (folder, glob) in COUNT_CLAIMS.items():
        actual = len(members(folder, glob))
        pattern = re.compile(rf"(\d+)\s+{re.escape(noun)}\b", re.IGNORECASE)
        for surface in SURFACES:
            text = read(surface)
            if text is None:
                continue
            for line in without_code(text).splitlines():
                if ASAT_MARKER in line:
                    continue
                for claim in pattern.finditer(line):
                    counted()
                    if int(claim.group(1)) != actual:
                        fail("count", f"{surface} claims {claim.group(1)} {noun}; {folder}/{glob} holds {actual}")


def check_catalog_coverage() -> None:
    """Both directions: the catalog names nothing missing, and nothing present is uncataloged.

    The second direction is the one that grows silently, and it is what makes this checker self-extending — a new file turns the build red until it is
    registered somewhere.
    """
    for index, (folder, glob) in CATALOGS.items():
        text = read(index)
        if text is None:
            continue
        body = without_code(text)
        for item in members(folder, glob):
            if item.name in CATALOG_EXEMPT or (ROOT / index).resolve() == item.resolve():
                continue
            counted()
            if item.name not in body:
                fail("coverage", f"{folder}/{item.name} exists but is not cataloged in {index}")


# --------------------------------------------------------------------------------------------------------------- TIER 2
# Keep a check below only while its trigger artifact exists. Delete the rest rather than leaving inert scaffolding.


def check_task_recipes() -> None:
    """Recipes named in prose exist in the task runner, and every cataloged script has a way to be run."""
    if TASK_RUNNER is None:
        return
    runner = read(TASK_RUNNER)
    if runner is None:
        fail("runner", f"{TASK_RUNNER} is configured but does not exist")
        counted()
        return
    recipes = {m.group(1) for m in re.finditer(r"^([a-zA-Z][\w-]*)\s*(?:[*+a-zA-Z_].*)?:(?!=)", runner, re.MULTILINE)}
    for surface in RUNNER_REFERENCES:
        text = read(surface)
        if text is None:
            continue
        for named in {m.group(1) for m in re.finditer(r"`just ([a-zA-Z][\w-]*)", without_code(text))}:
            counted()
            if named not in recipes:
                fail("runner", f"{surface} names recipe `{named}` which {TASK_RUNNER} does not define")

    # And the reverse: a recipe pointing at a script that no longer exists. Nothing reads a recipe until someone runs it, so a script deleted in a cleanup leaves
    # a recipe that looks live in `just --list` and fails only for whoever tries it. Found exactly that on 20260903 — `record-current` still invoked
    # scripts/sync_auto_company.py, deleted when upstream sync was retired, and the prose-to-recipe direction had no way to see it.
    for m in re.finditer(r"(scripts/[\w./-]+\.py)", runner):
        counted()
        if not (ROOT / m.group(1)).is_file():
            fail("runner", f"{TASK_RUNNER} invokes {m.group(1)}, which does not exist; the recipe is dead but still listed")


# --------------------------------------------------------------------------------------------------------------- TIER 3
# Project-specific invariants. Each check states, in its docstring, the project rule it enforces and where that rule lives. A check whose justification cannot
# be found is a check the next agent deletes.


# Manifest capability rows have a fixed inline-mapping shape, so they are read with a regex rather than PyYAML. This is deliberate: the governance gate is
# stdlib-only by doctrine ("a check that cannot run is indistinguishable from a check that passes"), and this project has already been bitten by exactly that —
# the skill-contract test failed on a missing PyYAML on 2026-09-01 because it had been supplied invisibly by the host interpreter. The richer YAML-aware
# validation lives in scripts/validate_agent_stack.py, which runs in the bootstrapped venv and may import yaml freely.
CAPABILITY_ROW = re.compile(
    r"^\s*-\s*\{id:\s*(?P<id>[^,]+),\s*kind:\s*(?P<kind>[^,]+),\s*path:\s*(?P<path>[^,]+),", re.MULTILINE
)


def manifest_capabilities() -> list[dict[str, str]]:
    text = read("manifest.yaml")
    if text is None:
        return []
    return [m.groupdict() for m in CAPABILITY_ROW.finditer(text)]


def check_manifest_paths_exist() -> None:
    """Every capability path in manifest.yaml resolves on disk.

    Rule: manifest.yaml is the install contract — README.md calls it "source paths, install convention, and the classification inventory", and
    scripts/install_global.py symlinks from it. A capability naming a path that does not exist becomes a broken global symlink on the next install.
    """
    for cap in manifest_capabilities():
        counted()
        if not (ROOT / cap["path"].strip()).exists():
            fail("manifest", f"capability `{cap['id'].strip()}` names path `{cap['path'].strip()}` which does not exist")


def check_manifest_covers_library() -> None:
    """Nothing in personas/ or skills/ is missing from manifest.yaml.

    The orphan direction, and the one that grows silently: an unregistered skill is invisible to the installer, the routing catalogue and the validator at once,
    so it ships as a file nobody links. Rule: README.md states the manifest IS the classification inventory, which is only true if it is complete.
    """
    registered = {cap["path"].strip() for cap in manifest_capabilities()}
    if not registered:
        return
    for folder, pattern in (("personas", "*.md"), ("skills", "*")):
        base = ROOT / folder
        if not base.is_dir():
            continue
        for entry in sorted(base.glob(pattern)):
            # A folder's own index is navigation, not a capability. CATALOG_EXEMPT already names the same file for the coverage check, so both checks
            # agree on what README.md is rather than each keeping a private opinion.
            if entry.name.startswith(".") or entry.name in CATALOG_EXEMPT:
                continue
            counted()
            if f"{folder}/{entry.name}" not in registered:
                fail("manifest", f"{folder}/{entry.name} exists but no manifest.yaml capability registers it")


def check_package_skills_have_skill_md() -> None:
    """Every capability of kind `package` contains a SKILL.md.

    Rule: SKILL_STANDARD.md, "Required metadata" — "Every package skill has `SKILL.md` with valid YAML frontmatter". Frontmatter VALIDITY is checked by
    skills/skill-creator/scripts/quick_validate.py under `just test`; this asserts only the structural precondition, which is what a missing file breaks first.
    """
    for cap in manifest_capabilities():
        if cap["kind"].strip() != "package":
            continue
        counted()
        if not (ROOT / cap["path"].strip() / "SKILL.md").is_file():
            fail("skill-contract", f"package `{cap['id'].strip()}` has no SKILL.md")


def check_library_counts() -> None:
    """Prose counts of skills/capabilities match the manifest.

    Skill packages are directories, so the generic COUNT_CLAIMS check (which globs files) cannot see them. Rule: README.md and REVISION_NOTES.md both state
    library sizes; a stale number here is how a reader learns the wrong inventory. Historical lines marked `count:asat` are evidence, not live claims, and are
    exempt.

    "Capability" carries two meanings in this repo since the 2026-09-01 routing taxonomy: a manifest capability is an installable entry (persona or skill), while
    a ROUTING capability is a taxonomy term that skills, personas and gates reference. Only the first is what this check counts, so a claim explicitly qualified
    as "routing capabilities" is skipped. The qualifier is required precisely because the bare noun is ambiguous — an unqualified count is still checked.
    """
    caps = manifest_capabilities()
    if not caps:
        return
    actual = {
        "skills": sum(1 for c in caps if c["kind"].strip() != "persona"),
        "capabilities": len(caps),
    }
    for noun, expected in actual.items():
        pattern = re.compile(rf"(\d+)\s+(?!routing\b)(?:current\s+|package\s+)?{noun}\b", re.IGNORECASE)
        for surface in SURFACES:
            text = read(surface)
            if text is None:
                continue
            for line in without_code(text).splitlines():
                if ASAT_MARKER in line:
                    continue
                for claim in pattern.finditer(line):
                    counted()
                    if int(claim.group(1)) != expected:
                        fail("count", f"{surface} claims {claim.group(1)} {noun}; manifest.yaml holds {expected}")


def check_status_markers_resolved() -> None:
    """No governed surface leaves a pending status marker standing after the thing it describes has landed.

    Rule: MEMORY.md and SCRATCHPAD.md are read as current truth, so "in flight", "pending", "TBD" or "awaiting" in a RESULTS table is not a note, it is a false
    statement about the project's state. Found 2026-09-01: MEMORY.md's baselines table still read `v3 | in flight` after v3 had completed and been classified a
    negative result, which is the single most misleading thing a truth document can do.

    Deliberately narrow: only table rows are checked. Prose legitimately says "the run in flight when X happened" as history, and a marker inside a `count:asat`
    line is a dated record.
    """
    PENDING = ("in flight", "in-flight", "pending", "tbd", "awaiting", "not yet run")
    for surface in ("MEMORY.md", "SCRATCHPAD.md"):
        text = read(surface)
        if text is None:
            continue
        for n, line in enumerate(without_code(text).splitlines(), 1):
            if not line.startswith("|") or ASAT_MARKER in line:
                continue
            low = line.lower()
            for marker in PENDING:
                if marker in low:
                    counted()
                    fail("status", f"{surface}:{n} table row still reports {marker!r}; resolve it or mark the line count:asat")
                    break
            else:
                counted()


def check_archcore_document_contract() -> None:
    """Every .archcore/ document declares a valid status and carries its provenance.

    Rule: `.archcore/README.md` — durable truth is the highest authority in this project, so a document there must say which of the three states it is in and
    where it came from. A document with no `Source:` cannot be traced back to what it was promoted from, and a status outside the set is a state nobody has
    defined the meaning of. Both are cheap to check and expensive to discover late.

    `superseded` is deliberately in the allowed set: an accepted document is superseded IN PLACE with a dated banner, never deleted, because the superseded
    reasoning is usually the part a later reader needs.
    """
    VALID = {"proposed", "accepted", "superseded"}
    base = ROOT / ".archcore"
    if not base.is_dir():
        return
    for doc in sorted(base.rglob("*.md")):
        if doc.name == "README.md":
            continue
        rel = doc.relative_to(ROOT).as_posix()
        head = doc.read_text().split("\n# ", 1)[0]
        counted()
        status = next((ln.split(":", 1)[1].strip() for ln in head.splitlines() if ln.startswith("Status:")), None)
        if status not in VALID:
            fail("archcore", f"{rel} declares status {status!r}; must be one of {sorted(VALID)}")
        counted()
        if not any(ln.startswith("Source:") for ln in head.splitlines()):
            fail("archcore", f"{rel} has no Source: line; a promoted document must name what it was promoted from")


def check_venv_outside_repo() -> None:
    """The maintenance venv is not created inside this repo.

    Rule: skills_stuff/AGENTS.md, "venv + ephemeral runtime placement" (2026-04-23) — a skill's venv belongs at skills-working-cache/<skill>/venv and "never
    inside skills_stuff/<skill>/". Regression guard: on 2026-09-01 the root .mise.toml declared `path = ".venv"`, so every `mise run` silently built a venv in
    the source tree. .gitignore hid it, which is what let it survive — the violation was invisible to git status and to every existing check.
    """
    text = read(".mise.toml")
    if text is None:
        return
    for match in re.finditer(r"_\.python\.venv\s*=\s*\{[^}]*path\s*=\s*\"([^\"]+)\"", text):
        counted()
        declared = match.group(1)
        if not declared.startswith("/") or Path(declared).is_relative_to(ROOT):
            fail(
                "storage-routing",
                f".mise.toml puts the venv at `{declared}` — it must be an absolute path outside the repo, "
                f"under skills-working-cache/agent-stack/",
            )


def check_interpreter_pinning() -> None:
    """No task recipe reaches an interpreter implicitly.

    Two defects, one root cause — the recipe does not say which interpreter it means:

    1. A BARE `python3`/`npx`/`ruby` resolves to whatever is on PATH, not to what .mise.toml pins.
    2. `mise exec -- python` resolves to the venv only while `_.python.venv` activation applies. It tests clean, reads
       as pinned, and degrades SILENTLY to the host interpreter when that activation stops holding. Observed here on
       2026-09-01: every recipe used `mise exec -- python` and resolved correctly, while .mise.toml simultaneously
       pointed the venv INSIDE the repo — the implicit form made both the pinning and the violation invisible.

    Recipes must address {{py}} by path and depend on `_require-venv`. Node has no venv layer, so `mise exec -- node` is the legitimate explicit form for it.

    Rule: the runtime-isolation section of skill-ai-it's SKILL.md, and the Runtime placement section of AGENTS.md.
    """
    text = read("justfile")
    if text is None:
        return
    for lineno, line in enumerate(text.splitlines(), 1):
        if not line.startswith((" ", "\t")):
            continue  # recipe bodies are indented; the header line is not a command
        stripped = line.strip()
        if stripped.startswith("#"):
            continue
        # Blank out quoted literals before scanning. An interpreter NAME inside a string is a label being printed, not a command being run — `printf 'python  '`
        # in the `runtimes` recipe is the case that found this. Blanking rather than deleting keeps every offset intact, so the reported column still points at
        # real source.
        stripped = re.sub(r"'[^']*'|\"[^\"]*\"", lambda m: " " * len(m.group(0)), stripped)
        counted()
        if re.search(r"mise\s+exec\b[^|;]*--\s+python", stripped):
            fail(
                "runtime",
                f"justfile:{lineno} reaches Python through an implicit `mise exec -- python` — address the venv "
                f"interpreter by path via {{{{py}}}} and guard it with _require-venv",
            )
        for match in re.finditer(r"(?<![-\w/])(python3?|npx|ruby)\b", stripped):
            if re.search(r"mise\s+(exec\b[^|;]*--|run)\s*$", stripped[: match.start()]):
                continue
            fail(
                "runtime",
                f"justfile:{lineno} calls bare `{match.group(1)}` — route it through the pinned interpreter",
            )


def check_derived_freshness() -> None:
    """Generated artifacts are not older than the sources they are generated from.

    Freshness only — it proves a rebuild happened, not that the rebuild used the right source. Where the generator can stamp its source into the output, add a
    provenance check alongside this one; see patterns/governance-checks.md.
    """
    for output, inputs in DERIVED.items():
        out = ROOT / output
        if not out.is_file():
            fail("derived", f"{output} is registered as generated but does not exist")
            counted()
            continue
        for src in inputs:
            source = ROOT / src
            counted()
            if not source.is_file():
                fail("derived", f"{output} declares input `{src}` which does not exist")
            elif out.stat().st_mtime < source.stat().st_mtime:
                fail("derived", f"{output} is older than its input `{src}` — regenerate it")


def check_constant_sync() -> None:
    """Facts restated across surfaces stay identical, and no unregistered file restates them.

    Duplication here is deliberate: the operator must read the value at the point of decision without following a pointer. So the duplication stays and the sync
    is enforced. Orphan detection is the half that makes it self-extending.
    """
    for name, entry in CONSTANT_SURFACES.items():
        pattern = re.compile(str(entry["pattern"]))
        registered = {str(s) for s in entry["surfaces"]}  # type: ignore[union-attr]
        owner = str(entry.get("owner", ""))

        for surface in sorted(registered):
            text = read(surface)
            counted()
            if text is None:
                fail("constant", f"{name}: registered surface {surface} does not exist")
            elif not pattern.search(without_code(text)):
                fail("constant", f"{name}: {surface} is registered but no longer states it (owner: {owner or 'unset'})")

        for path in sorted(ROOT.rglob("*")):
            if not path.is_file() or path.suffix not in SCAN_SUFFIXES:
                continue
            rel = path.relative_to(ROOT).as_posix()
            if rel in registered or rel.startswith(".") or "/." in rel or rel == SELF:
                continue
            counted()
            if pattern.search(without_code(path.read_text(encoding="utf-8", errors="ignore"))):
                fail("constant", f"{name}: {rel} states it but is not registered in CONSTANT_SURFACES")


def check_append_only_grain() -> None:
    """Every row of an append-only table stamps its pass, and no pass records the same entity twice.

    Registered in APPEND_ONLY_TABLES. Two distinct failures, both silent: a row with an EMPTY pass column cannot be ordered against any other row, so nothing
    can say which measurement is current; and a REPEATED (entity, pass) pair means one pass measured one entity twice, so every count and every aggregate over
    the table is wrong by however many rows were duplicated. Neither shows up as an error — the table still parses and the report still renders.

    A re-measurement is a NEW pass. Reusing the previous pass identifier to record one is the defect this catches.
    """
    for rel, (entity_col, pass_col) in APPEND_ONLY_TABLES.items():
        rows = table_rows(rel)
        if not rows:
            counted()
            if not (ROOT / rel).is_file():
                fail("append-only-grain", f"{rel} is registered as append-only but does not exist")
            continue
        seen: dict[tuple[str, str], int] = {}
        for i, row in enumerate(rows, start=2):  # line 1 is the header
            counted()
            if entity_col not in row or pass_col not in row:
                fail("append-only-grain",
                     f"{rel} has no {entity_col!r}/{pass_col!r} column; the registered grain does not match the table")
                break
            pass_id = (row.get(pass_col) or "").strip()
            if not pass_id:
                fail("append-only-grain", f"{rel} line {i} has empty {pass_col}; the pass is the grain")
                continue
            key = ((row.get(entity_col) or "").strip(), pass_id)
            if key in seen:
                fail("append-only-grain",
                     f"{rel} line {i} repeats {entity_col} {key[0]!r} for pass {pass_id} (first seen line {seen[key]}); "
                     f"a re-measurement is a NEW pass, so give it a new {pass_col}")
            else:
                seen[key] = i


def check_evidence_provenance() -> None:
    """Every markdown capture states where it came from, when, and whether the fetch succeeded.

    Enforces the global source-discipline policy (~/.agents/AGENTS.md, 'Citations travel into the documentation'): a VERIFIED figure means a capture exists that
    someone else can re-open. Presence of a capture FILE is not that — a file with no URL and no HTTP status proves only that somebody wrote something down.

    A capture missing the header is accepted ONLY while it names its correcting capture in EVIDENCE_PROVENANCE_CORRECTED and that capture is on disk.
    """
    if EVIDENCE_DIR is None:
        return
    for item in members(EVIDENCE_DIR, "*.md"):
        if item.name == EVIDENCE_INDEX:
            continue
        counted()
        text = read(f"{EVIDENCE_DIR}/{item.name}") or ""
        missing = [f for f in EVIDENCE_PROVENANCE_FIELDS if f"**{f}**" not in text]
        if not missing:
            continue
        corrector = EVIDENCE_PROVENANCE_CORRECTED.get(item.name)
        if corrector is None:
            fail("evidence-provenance",
                 f"{EVIDENCE_DIR}/{item.name} states no {', '.join(missing)}; a capture nobody can re-open is not evidence")
        elif not (ROOT / EVIDENCE_DIR / corrector).is_file():
            fail("evidence-provenance",
                 f"{EVIDENCE_DIR}/{item.name} defers its provenance to {corrector}, which does not exist")


# --------------------------------------------------------------------------------------------------------------- MAIN

def check_jsonl_evidence_contract() -> None:
    """Every line of a tracked JSONL evidence file parses and carries the keys its readers require.

    Registered in JSONL_EVIDENCE. These files cross a process boundary: one script appends, another aggregates days later. Both failures here are silent by
    construction — a reader skipping an unparseable line and a reader finding a key absent behave identically to a reader finding nothing to report.

    The `inadequate` rule is the load-bearing one. propose_evolution.py groups those gaps on the skill id BEFORE the colon, which is what makes the aggregation
    exact rather than a guess at what two sentences share. A declaration with no colon groups under its entire sentence, so it can never match another one, and
    a real repeated complaint about a skill silently never reaches the threshold that would surface it.
    """
    for rel, required in JSONL_EVIDENCE.items():
        path = ROOT / rel
        counted()
        if not path.is_file():
            fail("jsonl-evidence", f"{rel} is registered as JSONL evidence but does not exist")
            continue
        for i, line in enumerate(path.read_text().splitlines(), start=1):
            if not line.strip():
                continue
            counted()
            try:
                row = json.loads(line)
            except json.JSONDecodeError as e:
                fail("jsonl-evidence", f"{rel} line {i} does not parse: {e}")
                continue
            missing = [k for k in required if k not in row]
            if missing:
                fail("jsonl-evidence", f"{rel} line {i} is missing {', '.join(missing)}; a reader cannot tell it apart from no evidence at all")
            if rel.endswith("capability-gaps.jsonl"):
                if row.get("kind") not in ("missing", "inadequate"):
                    fail("jsonl-evidence", f"{rel} line {i} has kind {row.get('kind')!r}; expected 'missing' or 'inadequate'")
                if row.get("kind") == "inadequate" and ":" not in (row.get("text") or ""):
                    fail("jsonl-evidence",
                         f"{rel} line {i} declares a skill inadequate without naming it as '<skill-id>: <why>'; "
                         f"the proposer groups on the id before the colon, so this can never aggregate with another report of the same skill")


def check_skill_package_references() -> None:
    """Every in-package path a SKILL.md names — in prose OR in a command — resolves inside that package.

    THE HOLE THIS CLOSES. check_referenced_paths reads registered governance SURFACES, so until 20260903 no check had ever opened a `skills/*/SKILL.md` and asked
    whether its own references exist. A staleness audit that day found 11 across four packages: `skills/devops/SKILL.md` advertised a `### Scripts` section
    listing two automation scripts that were never imported, and `product-strategist` listed four reference files and four runnable scripts, none of which exist.
    An agent invoking one of those skills is told a capability is available and reaches for something that is not there — mid-task, with no error to read.

    COMMANDS INSIDE FENCES COUNT. `product-strategist`'s four were written as `python scripts/market_sizing.py ...` inside a ```bash block, which every
    prose-oriented scanner skips by construction. Five of the sixteen findings were only visible this way, which is the argument for checking the invocation form
    separately rather than trusting one pattern.

    An `<!-- claim-scan:examples -->` marker exempts a file whose paths are ILLUSTRATIVE — `skill-creator` teaches skill structure and names `references/finance.md`
    to show the shape, not to point at a file. The marker is the same one the audit tooling honours, so the two agree rather than each keeping a private list.
    """
    for md in sorted(ROOT.glob("skills/*/SKILL.md")):
        pkg = md.parent
        text = md.read_text(encoding="utf-8", errors="replace")
        counted()
        if EXAMPLE_MARKER in text:
            continue
        named: set[str] = set()
        prose = without_code(text)
        for m in re.finditer(r"`([^`\n]+)`", prose):
            named.add(m.group(1).strip())
        # The invocation form, read from the WHOLE file including fenced blocks — that is where it lives.
        for m in re.finditer(r"\b(?:python3?|bash|sh|node)\s+((?:scripts|assets|bin|templates|references|resources)/[\w./-]+)", text):
            named.add(m.group(1))
        for tok in sorted(named):
            if not tok.startswith(("scripts/", "assets/", "templates/", "references/", "resources/")):
                continue
            if not PATHLIKE.match(tok):
                continue
            counted()
            # Package-relative OR repo-relative. `skill-agent-stack` correctly names scripts/close_route.py at the repo root, and reading that as a
            # package path reported a defect that does not exist. Only a token resolving NOWHERE is a promise the agent cannot collect on.
            if not (pkg / tok).exists() and not (ROOT / tok).exists():
                fail("skill-refs", f"{md.relative_to(ROOT)} names {tok}, which exists neither in {pkg.name}/ nor at the repo root; "
                                  f"an agent invoking this skill is promised a capability that is absent")


def check_superseded_marked_in_index() -> None:
    """A document declaring `Status: superseded` says so in the index that routes readers to it.

    `.archcore/` is this project's HIGHEST authority — AI_NAVIGATION.md routes there first — so its index is the surface an agent reads before deciding which
    document is binding. On 20260903 that index listed four retired sync documents with no indication of their state: the banners were inside the files, and a
    reader scanning the index for the governing rule saw four live entries.

    This is the Phase 3 defect inverted. The usual failure is a supersession recorded in a routing table that never reaches the superseded file; here it reached
    the file and never reached the routing table. Both leave a reader acting on a retired rule, so both need the check.

    Derived from each document's own `Status:` line rather than a hand-kept list, because a hand-kept list of what is superseded drifts exactly as the thing it
    polices does.
    """
    index = ROOT / ".archcore" / "README.md"
    if not index.is_file():
        return
    body = index.read_text()
    for doc in sorted((ROOT / ".archcore").rglob("*.md")):
        if doc.name == "README.md":
            continue
        counted()
        if not re.search(r"^Status:\s*superseded\s*$", doc.read_text(encoding="utf-8", errors="replace"), re.M):
            continue
        rel = doc.relative_to(ROOT / ".archcore").as_posix()
        row = re.search(rf"^\|\s*\[([^\]]+)\]\({re.escape(rel)}\)", body, re.M)
        if row is None:
            fail("supersession", f".archcore/{rel} is superseded but the index does not link it at all")
        elif "SUPERSEDED" not in row.group(1).upper():
            fail("supersession", f".archcore/{rel} declares Status: superseded, but .archcore/README.md lists it as though it were live; "
                                 f"the index is where a reader decides which document binds")


def check_no_duplicate_yaml_keys() -> None:
    """No YAML mapping in this project defines the same key twice.

    A duplicate key is the quietest defect a structured file can carry: every parser accepts it, the last value wins, and the discarded block leaves no trace.
    Found on 20260903 in context-map.yaml, where the entry describing the file itself read `type: machine_routing_map` immediately followed by
    `type: sync_translation_rules` — two lines orphaned when upstream sync was retired. The file parsed cleanly and every consumer saw context-map.yaml
    described as a sync artifact that no longer exists, while the correct description was silently thrown away.

    Well-formedness proves nothing here, which is why this asserts on the KEY STREAM rather than on whether the load succeeds. Stdlib-only, so it hand-parses
    rather than importing PyYAML: this gate must never fail for an environment reason.
    """
    for rel in sorted(YAML_SURFACES):
        path = ROOT / rel
        counted()
        if not path.is_file():
            fail("yaml-keys", f"{rel} is registered as a YAML surface but does not exist")
            continue
        # Track keys per (indent, block). A new list item (`- `) or a dedent starts a fresh mapping.
        stack: dict[int, dict[str, int]] = {}
        for n, raw in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines(), start=1):
            if not raw.strip() or raw.lstrip().startswith("#"):
                continue
            indent = len(raw) - len(raw.lstrip())
            body = raw.lstrip()
            fresh = body.startswith("- ")
            if fresh:
                body = body[2:]
                indent += 2
            for deeper in [k for k in stack if k > indent]:
                del stack[deeper]
            if fresh:
                stack[indent] = {}
            m = re.match(r"([A-Za-z_][\w.-]*)\s*:(?:\s|$)", body)
            if not m:
                continue
            key = m.group(1)
            block = stack.setdefault(indent, {})
            counted()
            if key in block:
                fail("yaml-keys", f"{rel} line {n} repeats key {key!r} (first at line {block[key]}); "
                                 f"YAML keeps the LAST value and discards the first without any error")
            else:
                block[key] = n


CHECKS = (
    check_referenced_paths,
    check_index_links,
    check_count_claims,
    check_catalog_coverage,
    check_task_recipes,
    check_manifest_paths_exist,
    check_manifest_covers_library,
    check_package_skills_have_skill_md,
    check_library_counts,
    check_archcore_document_contract,
    check_status_markers_resolved,
    check_venv_outside_repo,
    check_interpreter_pinning,
    check_derived_freshness,
    check_constant_sync,
    check_append_only_grain,
    check_evidence_provenance,
    check_jsonl_evidence_contract,
    check_skill_package_references,
    check_superseded_marked_in_index,
    check_no_duplicate_yaml_keys,
)


def main() -> int:
    for check in CHECKS:
        check()

    # The same defect can be reported by more than one matching pattern; a doubled count erodes trust in the number.
    unique = sorted(set(failures))
    if unique:
        print(f"FAIL — {len(unique)} issue(s) across {checks_run} checks\n")
        for f in unique:
            print(f"  ✗ {f}")
        return 1

    print(f"OK — {checks_run} governance checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
