#!/usr/bin/env python3
"""Governance coherence checks for Agent Stack.

Turns this project's governance CLAIMS into assertions that fail. Stdlib only, so the gate never fails for environment reasons; exit 1 on any failure so it can
gate the task runner.

Generated by skill-ai-it from templates/check_governance.py. Doctrine, check families, and the inference table live in the skill's patterns/governance-checks.md
— read that before adding, changing, or retiring a check.

Structure:
  CONFIG      — registries the agent tunes per project. Everything below CONFIG is generic.
  Tier 1      — universal checks. Present in every project.
  Tier 2      — conditional checks. Kept only when their trigger artifact exists.
  Tier 3      — project-specific invariants. Authored per project; each cites the rule it enforces.

Growth rule: this file is expected to grow with the project. A new class of artifact needs a coverage check; a new duplicated constant needs a registry entry.
When a check fails, fix the project, not the check.

Checks:
  1. Referenced paths in the governance surfaces resolve on disk (relative to the referencing file, then to the repo root).
  2. Index links resolve, and every indexed folder member is linked.
  3. Count claims in prose match reality (historical facts exempt).
  4. Cataloged items exist and existing items are cataloged.
  5. Task-runner recipes named in prose exist in the runner.
  6. Derived artifacts are not older than their inputs.
  7. Every surface restating a registered constant states it identically, and nothing unregistered restates it.
  8. Every row of an append-only table stamps its pass, and no pass records the same entity twice.
  9. Every dated evidence capture states its URL, retrieval date and HTTP status, or names the capture that corrects it.

Since 2026-10-10 the checks live in the `govcheck` package beside this file, one module per family (skill-ai-it
`patterns/governance-checks.md`, "Structure and growth"); this file is the entry point. Options: --select FAMILY,... --json --timings.
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path


def main() -> int:
    """Run every check in order and report.

    Returns:
        0 when nothing failed, 1 otherwise.
    """
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    core = importlib.import_module("govcheck.core")
    checks = importlib.import_module("govcheck.checks")
    return core.run(checks.CHECKS)


if __name__ == "__main__":
    sys.exit(main())
